#!/usr/bin/env python3
"""
sync.py - Bidirectional agentic config compiler.

The `.ai/` folder is the durable source of truth for a repo's shared
Agentic Config Kit assets. Supported IDE-native files can also be used as
contribution surfaces: `adopt` imports them into `.ai/`, then `sync` exports
canonical equivalents for every supported IDE.

Usage:
    python3 .ai/sync.py                 # sync from .ai/
    python3 .ai/sync.py sync            # same
    python3 .ai/sync.py --check         # stale-output check, writes nothing
    python3 .ai/sync.py check           # same
    python3 .ai/sync.py doctor          # diagnose stale/native-only/degraded assets
    python3 .ai/sync.py adopt cursor .cursor/rules/foo.mdc
    python3 .ai/sync.py adopt --all
    python3 .ai/sync.py reconcile --all-exact
    python3 .ai/sync.py reconcile skill debug-word
    python3 .ai/sync.py clean
    python3 .ai/sync.py bootstrap

Python 3.6+ stdlib only.
"""

import argparse
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_AI_DIR = HERE
DEFAULT_REPO = os.path.dirname(DEFAULT_AI_DIR)
REPO = os.path.abspath(os.environ.get("AGENTIC_CONFIG_REPO_ROOT") or DEFAULT_REPO)
AI_DIR = os.path.abspath(os.environ.get("AGENTIC_CONFIG_AI_DIR") or DEFAULT_AI_DIR)


def rel_from_repo(path):
    ap = os.path.abspath(path)
    try:
        return os.path.relpath(ap, REPO).replace(os.sep, "/")
    except ValueError:
        return path.replace(os.sep, "/")


AI_REL = rel_from_repo(AI_DIR)
MANIFEST = os.path.join(AI_DIR, ".manifest.json")
MANIFEST_REL = "%s/.manifest.json" % AI_REL
COMMAND_NAME = os.environ.get("AGENTIC_CONFIG_COMMAND", "./sync-agentic.sh")
STEALTH_MODE = os.environ.get("AGENTIC_CONFIG_STEALTH") == "1"
STEALTH_SKIPS = []
GENERATOR_LABEL = "agentic-config"

TARGETS = ["claude", "cursor", "windsurf", "codex", "continue"]
KINDS = ["rule", "agent", "command", "skill"]
LIST_FIELDS = {
    "tools", "targets", "allowed-tools", "disallowed-tools", "globs",
    "paths", "arguments", "skills", "nickname_candidates",
}
BOOL_FIELDS = {
    "alwaysApply", "always_apply", "disable-model-invocation",
    "user-invocable", "invokable", "allow_implicit_invocation",
}
VALID_ACTIVATIONS = {"always_on", "model_decision", "glob", "manual"}

MARKER = "<!-- AUTOGENERATED from {src} by %s; do not edit. -->" % GENERATOR_LABEL
HASH_MARKER = "# AUTOGENERATED from {src} by %s; do not edit." % GENERATOR_LABEL
MANAGED_BEGIN = "<!-- BEGIN AGENTIC-CONFIG-KIT: {block} -->"
MANAGED_END = "<!-- END AGENTIC-CONFIG-KIT: {block} -->"
RULES_BLOCK = "rules"

SKILL_DIRS = {
    "claude": ".claude/skills",
    "cursor": ".cursor/skills",
    "windsurf": ".windsurf/skills",
    "codex": ".agents/skills",
}

GENERATED_PREFIXES = (
    ".claude/", ".cursor/", ".devin/", ".windsurf/",
    ".agents/", ".codex/agents/", ".continue/",
)


class SafetyError(Exception):
    pass


def relpath(path):
    return rel_from_repo(path)


def abspath(rel):
    return os.path.join(REPO, rel.replace("/", os.sep))


def source_rel(*parts):
    return "/".join([AI_REL] + [p.strip("/") for p in parts if p])


def add_stealth_skip(message):
    if message not in STEALTH_SKIPS:
        STEALTH_SKIPS.append(message)


def shell_quote(value):
    return shlex.quote(str(value))


def shell_command(parts):
    return " ".join(shell_quote(p) for p in parts)


def read_text(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def write_text(path, content):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def read_bytes(path):
    with open(path, "rb") as f:
        return f.read()


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def sha256_text(text):
    return sha256_bytes(text.encode("utf-8"))


def write_bytes(path, data):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)


def strip_quotes(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def parse_bool(value):
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in ("1", "true", "yes", "on")


def split_list(value):
    if isinstance(value, list):
        return value
    value = strip_quotes(str(value).strip())
    if value.startswith("[") and value.endswith("]"):
        try:
            parsed = json.loads(value.replace("'", '"'))
            if isinstance(parsed, list):
                return [str(x).strip() for x in parsed if str(x).strip()]
        except Exception:
            value = value[1:-1]
    if "," in value:
        parts = value.split(",")
    else:
        parts = value.split()
    return [strip_quotes(x.strip()) for x in parts if strip_quotes(x.strip())]


def parse_frontmatter(text, src, require=True):
    """Lenient frontmatter parser for simple Markdown/YAML-ish files."""
    if not text.startswith("---\n"):
        if require:
            raise ValueError("%s: file must begin with '---' frontmatter" % src)
        return {}, text

    lines = text.split("\n")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        if require:
            raise ValueError("%s: frontmatter is not closed with '---'" % src)
        return {}, text

    fm = {}
    for ln in lines[1:end]:
        if not ln.strip() or ln.lstrip().startswith("#"):
            continue
        if ":" not in ln:
            if require:
                raise ValueError("%s: malformed frontmatter line: %r" % (src, ln))
            continue
        key, val = ln.split(":", 1)
        key, val = key.strip(), val.strip()
        if key in LIST_FIELDS:
            fm[key] = split_list(val)
        elif key in BOOL_FIELDS:
            fm[key] = parse_bool(val)
        else:
            fm[key] = strip_quotes(val)
    body = "\n".join(lines[end + 1:])
    return fm, body


def first_paragraph(text):
    cleaned = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith(MANAGED_BEGIN.split("{")[0]):
            if cleaned:
                break
            continue
        cleaned.append(line)
    return " ".join(cleaned)[:180]


def slugify(name):
    name = os.path.splitext(os.path.basename(name))[0]
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9._-]+", "-", name)
    name = re.sub(r"-+", "-", name).strip("-")
    return name or "unnamed"


def normalize_activation(value):
    value = (value or "model_decision").strip().lower().replace("-", "_")
    aliases = {
        "always": "always_on",
        "alwaysapply": "always_on",
        "always_apply": "always_on",
        "auto": "model_decision",
        "agent_requested": "model_decision",
        "intelligent": "model_decision",
        "apply_intelligently": "model_decision",
        "specific_files": "glob",
        "auto_attached": "glob",
    }
    value = aliases.get(value, value)
    if value not in VALID_ACTIVATIONS:
        raise ValueError("unsupported activation %r (expected one of %s)" %
                         (value, ", ".join(sorted(VALID_ACTIVATIONS))))
    return value


def yaml_scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    s = str(value)
    needs_quote = (
        s == ""
        or s != s.strip()
        or ": " in s
        or " #" in s
        or s.endswith(":")
        or s[0] in "\"'[]{}#&*!|>%@`?,"
        or (s[0] == "-" and (len(s) == 1 or s[1] == " "))
        or s.lower() in {"true", "false", "yes", "no", "on", "off", "null", "~"}
    )
    return json.dumps(s, ensure_ascii=False) if needs_quote else s


def render_frontmatter(pairs):
    out = ["---"]
    for key, value in pairs:
        if value is None or value == "" or value == []:
            continue
        if isinstance(value, list):
            value = ", ".join(value)
        out.append("%s: %s" % (key, yaml_scalar(value)))
    out.append("---")
    return "\n".join(out)


def render_markdown(pairs, body, srcrel, marker=True):
    chunks = [render_frontmatter(pairs)]
    if marker:
        chunks.append(MARKER.format(src=srcrel))
    chunks.append(body.rstrip("\n"))
    return "\n".join(chunks).rstrip("\n") + "\n"


def render_canonical(asset):
    kind = asset["type"]
    pairs = [("name", asset["name"]), ("description", asset["description"])]
    if kind == "rule":
        pairs.extend([
            ("activation", asset.get("activation")),
            ("globs", asset.get("globs")),
            ("targets", asset.get("targets")),
        ])
    elif kind == "agent":
        pairs.extend([
            ("tools", asset.get("tools")),
            ("model", asset.get("model")),
            ("targets", asset.get("targets")),
        ])
    elif kind == "command":
        pairs.extend([
            ("argument-hint", asset.get("argument-hint")),
            ("model", asset.get("model")),
            ("targets", asset.get("targets")),
        ])
    elif kind == "skill":
        pairs.extend([
            ("allowed-tools", asset.get("allowed-tools")),
            ("targets", asset.get("targets")),
        ])
    return render_markdown(pairs, asset["body"], asset["srcrel"], marker=False)


def toml_string(value):
    return json.dumps(value or "", ensure_ascii=False)


def render_codex_agent(asset):
    lines = [
        'name = %s' % toml_string(asset["name"]),
        'description = %s' % toml_string(asset["description"]),
        'developer_instructions = %s' % toml_string(asset["body"].rstrip("\n")),
    ]
    if asset.get("model"):
        lines.append('model = %s' % toml_string(asset["model"]))
    return HASH_MARKER.format(src=asset["srcrel"]) + "\n" + "\n".join(lines) + "\n"


def render_codex_openai_yaml(display_name, short_description, implicit):
    body = [
        "interface:",
        "  display_name: %s" % yaml_scalar(display_name),
        "  short_description: %s" % yaml_scalar(short_description),
        "policy:",
        "  allow_implicit_invocation: %s" % ("true" if implicit else "false"),
        "",
    ]
    return "\n".join(body)


def codex_command_display_name(name):
    return "⚡ /%s" % name


def base_asset(kind, name, description, body, srcrel, fm=None, srcdir=None):
    fm = fm or {}
    asset = {
        "type": kind,
        "name": fm.get("name") or name,
        "description": description,
        "body": body,
        "srcrel": srcrel,
        "targets": fm.get("targets"),
        "tools": fm.get("tools"),
        "model": fm.get("model"),
        "argument-hint": fm.get("argument-hint"),
        "allowed-tools": fm.get("allowed-tools"),
        "disallowed-tools": fm.get("disallowed-tools"),
        "activation": normalize_activation(fm.get("activation") or fm.get("trigger")),
        "globs": fm.get("globs") or fm.get("paths"),
        "aux": {},
    }
    if kind != "rule":
        asset["activation"] = None
        asset["globs"] = None
    if srcdir is not None:
        for root, _dirs, files in os.walk(srcdir):
            for f in files:
                if root == srcdir and f == "SKILL.md":
                    continue
                if f == ".DS_Store":
                    continue
                ap = os.path.join(root, f)
                rel = os.path.relpath(ap, srcdir).replace(os.sep, "/")
                asset["aux"][rel] = ap
    return asset


def load_markdown_asset(kind, name, path, srcrel, srcdir=None):
    text = read_text(path)
    fm, body = parse_frontmatter(text, srcrel, require=True)
    description = fm.get("description")
    if not description:
        raise ValueError("%s: missing required 'description'" % srcrel)
    return base_asset(kind, name, description, body, srcrel, fm=fm, srcdir=srcdir)


def load_assets():
    assets = []

    rdir = os.path.join(AI_DIR, "rules")
    for f in sorted(os.listdir(rdir)) if os.path.isdir(rdir) else []:
        if f.endswith(".md"):
            assets.append(load_markdown_asset(
                "rule", f[:-3], os.path.join(rdir, f), source_rel("rules", f)))

    adir = os.path.join(AI_DIR, "agents")
    for f in sorted(os.listdir(adir)) if os.path.isdir(adir) else []:
        if f.endswith(".md"):
            assets.append(load_markdown_asset(
                "agent", f[:-3], os.path.join(adir, f), source_rel("agents", f)))

    cdir = os.path.join(AI_DIR, "commands")
    for f in sorted(os.listdir(cdir)) if os.path.isdir(cdir) else []:
        if f.endswith(".md"):
            assets.append(load_markdown_asset(
                "command", f[:-3], os.path.join(cdir, f), source_rel("commands", f)))

    sdir = os.path.join(AI_DIR, "skills")
    for d in sorted(os.listdir(sdir)) if os.path.isdir(sdir) else []:
        skill_md = os.path.join(sdir, d, "SKILL.md")
        if os.path.isfile(skill_md):
            assets.append(load_markdown_asset(
                "skill", d, skill_md, source_rel("skills", d, "SKILL.md"),
                srcdir=os.path.join(sdir, d)))

    assets.sort(key=lambda a: (a["type"], a["name"]))
    return assets


def target_allowed(asset, target):
    targets = asset.get("targets")
    return not targets or target in targets


def skill_pairs(asset, name=None, description=None, explicit_only=False):
    return [
        ("name", name or asset["name"]),
        ("description", description or asset["description"]),
        ("allowed-tools", asset.get("allowed-tools")),
        ("disable-model-invocation", True if explicit_only else None),
    ]


def rule_skill_body(asset):
    lines = [
        "# Rule: %s" % asset["name"],
        "",
        "Activation: %s" % asset.get("activation", "model_decision"),
    ]
    if asset.get("globs"):
        lines.append("Globs: %s" % ", ".join(asset["globs"]))
    lines.extend(["", asset["body"].rstrip("\n")])
    return "\n".join(lines).rstrip("\n") + "\n"


def rule_managed_block(rules):
    if not rules:
        return ""
    parts = [
        "# Agentic Config Rules",
        "",
        "This section is generated from `%s/rules/` by `%s`." % (AI_REL, GENERATOR_LABEL),
        "Edit canonical rules in `%s/rules/`, not here." % AI_REL,
        "",
    ]
    for asset in rules:
        parts.append("## %s" % asset["name"])
        parts.append("")
        parts.append("- Description: %s" % asset["description"])
        parts.append("- Activation: %s" % asset.get("activation", "model_decision"))
        if asset.get("globs"):
            parts.append("- Globs: %s" % ", ".join(asset["globs"]))
        parts.append("")
        parts.append(asset["body"].rstrip("\n"))
        parts.append("")
    return "\n".join(parts).rstrip("\n") + "\n"


def outputs_for(asset, target):
    t, n, desc, body, src = (
        asset["type"], asset["name"], asset["description"],
        asset["body"], asset["srcrel"])
    texts, copies, degradations = {}, {}, []

    if t == "rule":
        activation = asset.get("activation") or "model_decision"
        globs = asset.get("globs")
        if target == "claude":
            pairs = [("name", n), ("description", desc),
                     ("activation", activation), ("paths", globs)]
            texts[".claude/rules/%s.md" % n] = render_markdown(pairs, body, src)
        elif target == "cursor":
            always = activation == "always_on"
            pairs = [("description", desc if activation == "model_decision" else desc),
                     ("globs", globs if activation == "glob" else None),
                     ("alwaysApply", always)]
            texts[".cursor/rules/%s.mdc" % n] = render_markdown(pairs, body, src)
        elif target == "windsurf":
            pairs = [("trigger", activation), ("description", desc),
                     ("globs", globs if activation == "glob" else None)]
            texts[".devin/rules/%s.md" % n] = render_markdown(pairs, body, src)
        elif target == "codex":
            if activation != "always_on":
                dn = "rule-%s" % n
                skill_body = rule_skill_body(asset)
                texts[".agents/skills/%s/SKILL.md" % dn] = render_markdown(
                    [("name", dn), ("description", desc),
                     ("disable-model-invocation", activation == "manual")],
                    skill_body, src)
                texts[".agents/skills/%s/agents/openai.yaml" % dn] = (
                    HASH_MARKER.format(src=src) + "\n" +
                    render_codex_openai_yaml("Rule: %s" % n, desc,
                                             activation != "manual"))
            degradations.append("codex: rule %s also appears in managed AGENTS.md" % n)
        elif target == "continue":
            dn = "rule-%s" % n
            texts[".continue/prompts/%s.md" % dn] = render_markdown(
                [("name", dn), ("description", desc), ("invokable", True)],
                rule_skill_body(asset), src)
            degradations.append("continue: rule %s is available as a prompt" % n)

    elif t == "agent":
        if target == "claude":
            pairs = [("name", n), ("description", desc),
                     ("tools", asset.get("tools")), ("model", asset.get("model"))]
            texts[".claude/agents/%s.md" % n] = render_markdown(pairs, body, src)
        elif target == "cursor":
            texts[".cursor/agents/%s.md" % n] = render_markdown(
                [("name", n), ("description", desc)], body, src)
        elif target == "windsurf":
            dn = "agent-%s" % n
            texts[".windsurf/skills/%s/SKILL.md" % dn] = render_markdown(
                [("name", dn), ("description", desc)], body, src)
            degradations.append("windsurf: agent %s is exported as a skill" % n)
        elif target == "codex":
            texts[".codex/agents/%s.toml" % n] = render_codex_agent(asset)
        elif target == "continue":
            dn = "agent-%s" % n
            texts[".continue/prompts/%s.md" % dn] = render_markdown(
                [("name", dn), ("description", desc), ("invokable", True)],
                body, src)
            degradations.append("continue: agent %s is exported as a prompt" % n)

    elif t == "command":
        if target == "claude":
            texts[".claude/commands/%s.md" % n] = render_markdown(
                [("description", desc), ("argument-hint", asset.get("argument-hint")),
                 ("model", asset.get("model"))], body, src)
            texts[".claude/skills/%s/SKILL.md" % n] = render_markdown(
                [("name", n), ("description", desc),
                 ("argument-hint", asset.get("argument-hint")),
                 ("disable-model-invocation", True)], body, src)
        elif target == "cursor":
            texts[".cursor/commands/%s.md" % n] = render_markdown(
                [("description", desc), ("argument-hint", asset.get("argument-hint"))],
                body, src)
        elif target == "windsurf":
            texts[".windsurf/workflows/%s.md" % n] = render_markdown(
                [("name", n), ("description", desc)], body, src)
        elif target == "codex":
            dn = "command-%s" % n
            texts[".agents/skills/%s/SKILL.md" % dn] = render_markdown(
                [("name", dn), ("description", desc),
                 ("argument-hint", asset.get("argument-hint")),
                 ("disable-model-invocation", True)], body, src)
            texts[".agents/skills/%s/agents/openai.yaml" % dn] = (
                HASH_MARKER.format(src=src) + "\n" +
                render_codex_openai_yaml(codex_command_display_name(n), desc, False))
            degradations.append("codex: command %s is exported as an explicit skill" % n)
        elif target == "continue":
            texts[".continue/prompts/%s.md" % n] = render_markdown(
                [("name", n), ("description", desc), ("invokable", True)],
                body, src)

    elif t == "skill":
        if target in SKILL_DIRS:
            base = "%s/%s" % (SKILL_DIRS[target], n)
            texts["%s/SKILL.md" % base] = render_markdown(
                [("name", n), ("description", desc),
                 ("allowed-tools", asset.get("allowed-tools"))], body, src)
            for rel, ap in asset["aux"].items():
                copies["%s/%s" % (base, rel)] = ap
        elif target == "continue":
            texts[".continue/prompts/%s.md" % n] = render_markdown(
                [("name", n), ("description", desc), ("invokable", True)],
                body, src)
            degradations.append("continue: skill %s is exported as a prompt" % n)

    return texts, copies, degradations


def manifest_entry(path, source, kind, target, mode="file", block=None, content_hash=None):
    entry = {
        "path": path,
        "source": source,
        "kind": kind,
        "target": target,
        "mode": mode,
    }
    if block:
        entry["block"] = block
    if content_hash:
        entry["hash"] = content_hash
    return entry


def git_tracked_paths():
    try:
        out = subprocess.check_output(
            ["git", "ls-files", "-z"], cwd=REPO, stderr=subprocess.DEVNULL)
    except Exception:
        return set()
    return set(p for p in out.decode("utf-8").split("\0") if p)


def filter_stealth_tracked_outputs(texts, copies, managed, entries):
    if not STEALTH_MODE:
        return
    tracked = git_tracked_paths()
    if not tracked:
        return

    skipped_paths = set()
    for p in sorted(list(texts.keys())):
        if p in tracked:
            skipped_paths.add(p)
            del texts[p]
            add_stealth_skip(
                "%s is tracked; stealth mode skipped generated output for this path." % p)
    for p in sorted(list(copies.keys())):
        if p in tracked:
            skipped_paths.add(p)
            del copies[p]
            add_stealth_skip(
                "%s is tracked; stealth mode skipped generated output for this path." % p)
    for p in sorted(list(managed.keys())):
        if p in tracked:
            skipped_paths.add(p)
            del managed[p]
            if p == "AGENTS.md":
                add_stealth_skip(
                    "AGENTS.md is tracked; stealth mode skipped Codex managed rules "
                    "for this file. Use normal init or manual adoption for full Codex fidelity.")
            else:
                add_stealth_skip(
                    "%s is tracked; stealth mode skipped managed output for this path." % p)

    if skipped_paths:
        entries[:] = [
            e for e in entries
            if e.get("path") not in skipped_paths
        ]


def build(assets):
    names = {}
    for asset in assets:
        key = asset["name"]
        if key in names:
            raise SystemExit(
                "ERROR: duplicate asset name '%s' (%s and %s). Names must be "
                "unique across rules, agents, commands, and skills." %
                (key, names[key], asset["type"]))
        names[key] = asset["type"]

    texts, copies, entries, degradations = {}, {}, [], []

    def claim(path, where):
        if path in texts or path in copies:
            raise SystemExit("ERROR: output collision at '%s' (from %s)." %
                             (path, where))

    for asset in assets:
        for target in TARGETS:
            if not target_allowed(asset, target):
                continue
            ot, oc, od = outputs_for(asset, target)
            for p, content in sorted(ot.items()):
                claim(p, asset["srcrel"])
                texts[p] = content
                entries.append(manifest_entry(
                    p, asset["srcrel"], asset["type"], target,
                    content_hash=sha256_text(content)))
            for p, src in sorted(oc.items()):
                claim(p, asset["srcrel"])
                copies[p] = src
                entries.append(manifest_entry(
                    p, asset["srcrel"], asset["type"], target,
                    content_hash=sha256_bytes(read_bytes(src))))
            degradations.extend(od)

    codex_rules = [
        a for a in assets
        if a["type"] == "rule" and target_allowed(a, "codex")
    ]
    managed = {}
    if codex_rules:
        managed["AGENTS.md"] = {RULES_BLOCK: rule_managed_block(codex_rules)}
        entries.append(manifest_entry(
            "AGENTS.md", source_rel("rules"), "rule", "codex",
            mode="managed-block", block=RULES_BLOCK))

    filter_stealth_tracked_outputs(texts, copies, managed, entries)
    entries.sort(key=lambda e: (e["path"], e.get("block", ""), e["source"]))
    return texts, copies, managed, entries, sorted(set(degradations))


def read_manifest_entries():
    if not os.path.isfile(MANIFEST):
        return []
    try:
        data = json.load(open(MANIFEST, encoding="utf-8"))
    except Exception:
        return []
    outputs = data.get("outputs", [])
    entries = []
    for item in outputs:
        if isinstance(item, str):
            entries.append(manifest_entry(item, "", "", "", mode="file"))
        elif isinstance(item, dict) and item.get("path"):
            entries.append(item)
    return entries


def manifest_content(entries):
    return json.dumps({"version": 2, "outputs": entries},
                      indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def managed_block_text(block, content):
    return (MANAGED_BEGIN.format(block=block) + "\n" +
            MARKER.format(src=source_rel("rules")) + "\n\n" +
            content.rstrip("\n") + "\n" +
            MANAGED_END.format(block=block) + "\n")


def apply_managed_block(existing, block, content):
    begin = MANAGED_BEGIN.format(block=block)
    end = MANAGED_END.format(block=block)
    pattern = re.compile(
        r"\n?%s\n.*?\n%s\n?" % (re.escape(begin), re.escape(end)),
        re.DOTALL)
    replacement = managed_block_text(block, content) if content else ""
    if pattern.search(existing):
        def repl(match):
            if not replacement:
                return "\n" if match.group(0).startswith("\n") else ""
            prefix = "\n" if match.group(0).startswith("\n") else ""
            return prefix + replacement
        updated = pattern.sub(repl, existing)
    elif replacement:
        sep = "\n\n" if existing.rstrip("\n") else ""
        updated = existing.rstrip("\n") + sep + replacement
    else:
        updated = existing
    return re.sub(r"\n{4,}", "\n\n\n", updated).rstrip("\n") + ("\n" if updated else "")


def expected_managed_content(path, blocks):
    ap = abspath(path)
    existing = read_text(ap) if os.path.isfile(ap) else ""
    updated = existing
    for block, content in sorted(blocks.items()):
        updated = apply_managed_block(updated, block, content)
    return updated


def prune_empty_dirs(rel_paths):
    for rp in rel_paths:
        d = os.path.dirname(abspath(rp))
        while os.path.commonpath([d, REPO]) == REPO and d != REPO and os.path.isdir(d):
            if os.listdir(d):
                break
            os.rmdir(d)
            d = os.path.dirname(d)


def manifest_files_by_path(entries):
    by_path = {}
    for entry in entries:
        if entry.get("mode", "file") == "file" and entry.get("path"):
            by_path[entry["path"]] = entry
    return by_path


def existing_matches_manifest_hash(rel, entry):
    if not entry or not entry.get("hash"):
        return False
    ap = abspath(rel)
    if not os.path.isfile(ap):
        return False
    return sha256_bytes(read_bytes(ap)) == entry.get("hash")


def assert_safe_file_mutation(rel, old_entry, action):
    ap = abspath(rel)
    if not os.path.exists(ap):
        return
    if not os.path.isfile(ap):
        raise SafetyError(
            "refusing to %s %s because that path exists and is not a file" %
            (action, rel))
    if has_marker(rel) or existing_matches_manifest_hash(rel, old_entry):
        return
    raise SafetyError(
        "refusing to %s markerless file at generated path %s. "
        "Run %s doctor and adopt/reconcile it first, or remove it manually." %
        (action, rel, COMMAND_NAME))


def preflight_file_mutations(texts, copies, old_entries, new_file_paths):
    old_files = manifest_files_by_path(old_entries)
    tracked = git_tracked_paths() if STEALTH_MODE else set()
    for p, content in sorted(texts.items()):
        ap = abspath(p)
        if os.path.isfile(ap) and read_text(ap) == content:
            continue
        assert_safe_file_mutation(p, old_files.get(p), "overwrite")
    for p, src in sorted(copies.items()):
        ap = abspath(p)
        if os.path.isfile(ap) and read_bytes(ap) == read_bytes(src):
            continue
        assert_safe_file_mutation(p, old_files.get(p), "overwrite")
    for entry in old_entries:
        if entry.get("mode", "file") != "file":
            continue
        p = entry.get("path")
        if p and p not in new_file_paths and os.path.exists(abspath(p)):
            if STEALTH_MODE and p in tracked:
                add_stealth_skip(
                    "%s is tracked; stealth mode skipped pruning stale generated output." % p)
                continue
            assert_safe_file_mutation(p, entry, "prune")
    return old_files


def compare_outputs(texts, copies, managed, entries):
    drift = []
    tracked = git_tracked_paths() if STEALTH_MODE else set()
    for p, content in sorted(texts.items()):
        ap = abspath(p)
        if not os.path.isfile(ap) or read_text(ap) != content:
            drift.append(p)
    for p, src in sorted(copies.items()):
        ap = abspath(p)
        if not os.path.isfile(ap) or read_bytes(ap) != read_bytes(src):
            drift.append(p)
    for p, blocks in sorted(managed.items()):
        ap = abspath(p)
        expected = expected_managed_content(p, blocks)
        if not os.path.isfile(ap) or read_text(ap) != expected:
            drift.append("%s (managed block)" % p)

    old_entries = read_manifest_entries()
    new_file_paths = set(list(texts.keys()) + list(copies.keys()))
    new_managed = set((p, b) for p, blocks in managed.items() for b in blocks)
    for entry in old_entries:
        mode = entry.get("mode", "file")
        p = entry.get("path")
        if mode == "managed-block":
            key = (p, entry.get("block"))
            if key not in new_managed and os.path.isfile(abspath(p)):
                if STEALTH_MODE and p in tracked:
                    add_stealth_skip(
                        "%s is tracked; stealth mode skipped pruning stale managed output." % p)
                    continue
                existing = read_text(abspath(p))
                begin = MANAGED_BEGIN.format(block=entry.get("block"))
                if begin in existing:
                    drift.append("%s (stale managed block)" % p)
        elif p and p not in new_file_paths and os.path.exists(abspath(p)):
            if STEALTH_MODE and p in tracked:
                add_stealth_skip(
                    "%s is tracked; stealth mode skipped pruning stale generated output." % p)
                continue
            drift.append("%s (stale; should be pruned)" % p)

    cur_manifest = read_text(MANIFEST) if os.path.isfile(MANIFEST) else ""
    new_manifest = manifest_content(entries)
    if cur_manifest != new_manifest:
        drift.append(MANIFEST_REL)
    return drift


def write_outputs(texts, copies, managed, entries):
    old_entries = read_manifest_entries()
    tracked = git_tracked_paths() if STEALTH_MODE else set()
    new_file_paths = set(list(texts.keys()) + list(copies.keys()))
    new_managed = set((p, b) for p, blocks in managed.items() for b in blocks)
    old_files = preflight_file_mutations(texts, copies, old_entries, new_file_paths)
    created = updated = 0

    for p, content in sorted(texts.items()):
        ap = abspath(p)
        if os.path.isfile(ap) and read_text(ap) == content:
            continue
        assert_safe_file_mutation(p, old_files.get(p), "overwrite")
        existed = os.path.exists(ap)
        write_text(ap, content)
        created += 0 if existed else 1
        updated += 1 if existed else 0

    for p, src in sorted(copies.items()):
        ap = abspath(p)
        data = read_bytes(src)
        if os.path.isfile(ap) and read_bytes(ap) == data:
            continue
        assert_safe_file_mutation(p, old_files.get(p), "overwrite")
        existed = os.path.exists(ap)
        write_bytes(ap, data)
        created += 0 if existed else 1
        updated += 1 if existed else 0

    managed_updated = 0
    for p, blocks in sorted(managed.items()):
        ap = abspath(p)
        expected = expected_managed_content(p, blocks)
        if os.path.isfile(ap) and read_text(ap) == expected:
            continue
        write_text(ap, expected)
        managed_updated += 1

    pruned = []
    for entry in old_entries:
        mode = entry.get("mode", "file")
        p = entry.get("path")
        if not p:
            continue
        if mode == "managed-block":
            block = entry.get("block")
            if (p, block) not in new_managed and os.path.isfile(abspath(p)):
                if STEALTH_MODE and p in tracked:
                    add_stealth_skip(
                        "%s is tracked; stealth mode skipped pruning stale managed output." % p)
                    continue
                existing = read_text(abspath(p))
                updated_content = apply_managed_block(existing, block, "")
                if updated_content != existing:
                    write_text(abspath(p), updated_content)
                    pruned.append("%s (%s block)" % (p, block))
        elif p not in new_file_paths and os.path.exists(abspath(p)):
            if STEALTH_MODE and p in tracked:
                add_stealth_skip(
                    "%s is tracked; stealth mode skipped pruning stale generated output." % p)
                continue
            assert_safe_file_mutation(p, entry, "prune")
            os.remove(abspath(p))
            pruned.append(p)
    prune_empty_dirs([p.split(" (", 1)[0] for p in pruned])

    new_manifest = manifest_content(entries)
    if not os.path.isfile(MANIFEST) or read_text(MANIFEST) != new_manifest:
        write_text(MANIFEST, new_manifest)

    return created, updated, managed_updated, pruned


def print_stealth_skips():
    if not STEALTH_SKIPS:
        return
    print("Stealth skipped tracked outputs:")
    for item in STEALTH_SKIPS:
        print("  %s" % item)


def command_sync(check=False):
    assets = load_assets()
    texts, copies, managed, entries, _degradations = build(assets)
    if check:
        drift = compare_outputs(texts, copies, managed, entries)
        if drift:
            print("Generated IDE folders are STALE vs %s master:" % AI_REL)
            for d in drift:
                print("    %s" % d)
            print("\nRun %s to regenerate local projections and refresh the manifest." % COMMAND_NAME)
            print_stealth_skips()
            return 1
        print("In sync: %d generated entries match %s master." % (len(entries), AI_REL))
        print_stealth_skips()
        return 0

    try:
        created, updated, managed_updated, pruned = write_outputs(texts, copies, managed, entries)
    except SafetyError as e:
        print("ERROR: %s" % e)
        return 1
    by_type = {}
    for asset in assets:
        by_type[asset["type"]] = by_type.get(asset["type"], 0) + 1
    summary = ", ".join("%d %ss" % (by_type[k], k) for k in sorted(by_type))
    print("Synced %d canonical assets (%s) -> %d manifest entries across %d IDEs." %
          (len(assets), summary, len(entries), len(TARGETS)))
    print("  created %d, updated %d, managed %d, pruned %d." %
          (created, updated, managed_updated, len(pruned)))
    for p in pruned:
        print("  pruned %s" % p)
    print_stealth_skips()
    return 0


def has_marker(rel):
    ap = abspath(rel)
    if not os.path.isfile(ap):
        return False
    try:
        return "AUTOGENERATED from" in read_text(ap)
    except UnicodeDecodeError:
        return False


def detect_native(ide, rel):
    rel = rel.replace(os.sep, "/")
    if ide == "cursor":
        if rel.startswith(".cursor/rules/") and rel.endswith(".mdc"):
            return "rule"
        if rel.startswith(".cursor/commands/") and rel.endswith(".md"):
            return "command"
        if rel.startswith(".cursor/agents/") and rel.endswith(".md"):
            return "agent"
        if rel.startswith(".cursor/skills/") and rel.endswith("/SKILL.md"):
            return "skill"
    if ide == "windsurf":
        if (rel.startswith(".devin/rules/") or rel.startswith(".windsurf/rules/")) and rel.endswith(".md"):
            return "rule"
        if rel.startswith(".windsurf/workflows/") and rel.endswith(".md"):
            return "command"
        if rel.startswith(".windsurf/skills/") and rel.endswith("/SKILL.md"):
            return "skill"
    if ide == "codex":
        if rel.startswith(".codex/rules/") and rel.endswith(".rules"):
            return "unsupported-policy"
        if rel.startswith(".agents/skills/") and rel.endswith("/SKILL.md"):
            return "skill"
        if rel.startswith(".codex/agents/") and rel.endswith(".toml"):
            return "agent"
    if ide == "claude":
        if rel.startswith(".claude/rules/") and rel.endswith(".md"):
            return "rule"
        if rel.startswith(".claude/commands/") and rel.endswith(".md"):
            return "command"
        if rel.startswith(".claude/agents/") and rel.endswith(".md"):
            return "agent"
        if rel.startswith(".claude/skills/") and rel.endswith("/SKILL.md"):
            return "skill"
    if ide == "continue":
        if rel.startswith(".continue/prompts/") and rel.endswith(".md"):
            return "command"
    return None


def ide_from_path(rel):
    if rel.startswith(".cursor/"):
        return "cursor"
    if rel.startswith(".windsurf/") or rel.startswith(".devin/"):
        return "windsurf"
    if rel.startswith(".agents/") or rel.startswith(".codex/"):
        return "codex"
    if rel.startswith(".claude/"):
        return "claude"
    if rel.startswith(".continue/"):
        return "continue"
    return None


def native_name(kind, rel):
    parts = rel.split("/")
    if kind == "skill":
        return parts[-2]
    if kind == "agent" and rel.endswith(".toml"):
        return slugify(parts[-1])
    return slugify(parts[-1])


def strip_marker(body):
    lines = body.splitlines()
    lines = [ln for ln in lines if "AUTOGENERATED from" not in ln]
    return "\n".join(lines).strip("\n") + "\n"


def parse_simple_toml_agent(text, src):
    values = {}
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        i += 1
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, val = line.split("=", 1)
        key, val = key.strip(), val.strip()
        if val.startswith('"""'):
            collected = [val[3:]]
            while i < len(lines) and not collected[-1].endswith('"""'):
                collected.append(lines[i])
                i += 1
            joined = "\n".join(collected)
            if joined.endswith('"""'):
                joined = joined[:-3]
            values[key] = joined
        else:
            try:
                values[key] = json.loads(val)
            except Exception:
                values[key] = strip_quotes(val)
    body = values.get("developer_instructions") or values.get("prompt") or ""
    desc = values.get("description") or first_paragraph(body) or "Imported Codex agent."
    fm = {"name": values.get("name"), "description": desc, "model": values.get("model")}
    return base_asset("agent", values.get("name") or slugify(src), desc, body, src, fm=fm)


def cursor_activation(fm):
    if parse_bool(fm.get("alwaysApply", False)):
        return "always_on"
    if fm.get("globs"):
        return "glob"
    if fm.get("description"):
        return "model_decision"
    return "manual"


def native_to_asset(ide, rel, kind):
    ap = abspath(rel)
    text = read_text(ap)
    if kind == "unsupported-policy":
        raise ValueError("%s is a Codex execution policy, not portable behavioral guidance" % rel)
    if kind == "agent" and ide == "codex" and rel.endswith(".toml"):
        return parse_simple_toml_agent(text, rel)

    fm, body = parse_frontmatter(text, rel, require=False)
    body = strip_marker(body)
    name = fm.get("name") or native_name(kind, rel)
    description = fm.get("description") or first_paragraph(body) or "Imported %s from %s." % (kind, ide)

    if ide == "cursor" and kind == "rule":
        fm["activation"] = cursor_activation(fm)
    elif ide == "windsurf" and kind == "rule":
        fm["activation"] = fm.get("trigger") or fm.get("activation") or "model_decision"
    elif kind == "rule":
        fm["activation"] = fm.get("activation") or "model_decision"

    if ide == "codex" and kind == "skill" and name.startswith("command-"):
        kind = "command"
        name = name[len("command-"):]
    elif ide == "codex" and kind == "skill" and name.startswith("rule-"):
        kind = "rule"
        name = name[len("rule-"):]
        fm["activation"] = "manual" if parse_bool(fm.get("disable-model-invocation", False)) else "model_decision"

    srcdir = os.path.dirname(ap) if kind == "skill" else None
    return base_asset(kind, name, description, body, rel, fm=fm, srcdir=srcdir)


def canonical_rel(asset):
    kind, name = asset["type"], asset["name"]
    if kind == "skill":
        return source_rel("skills", name, "SKILL.md")
    return source_rel("%ss" % kind, "%s.md" % name)


def copy_skill_aux(asset, dest_dir):
    for rel, src in sorted(asset.get("aux", {}).items()):
        dst = os.path.join(dest_dir, rel.replace("/", os.sep))
        if os.path.exists(dst) and read_bytes(dst) != read_bytes(src):
            raise ValueError("canonical aux conflict at %s" % relpath(dst))
        write_bytes(dst, read_bytes(src))


def normalize_body(text):
    lines = []
    for line in strip_marker(text).replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        lines.append(line.rstrip())
    return "\n".join(lines).strip() + "\n"


def normalized_list(value):
    return sorted(value or [])


def aux_hashes(asset):
    hashes = []
    for rel, path in sorted(asset.get("aux", {}).items()):
        hashes.append([rel, hashlib.sha256(read_bytes(path)).hexdigest()])
    return hashes


def fingerprint_payload(asset):
    kind = asset["type"]
    meta = {
        "type": kind,
        "name": asset["name"],
        "description": asset["description"],
        "body": normalize_body(asset["body"]),
        "aux": aux_hashes(asset),
    }
    if kind == "rule":
        meta["activation"] = asset.get("activation") or "model_decision"
        meta["globs"] = normalized_list(asset.get("globs"))
    elif kind == "agent":
        meta["tools"] = normalized_list(asset.get("tools"))
        meta["model"] = asset.get("model") or ""
    elif kind == "command":
        meta["argument-hint"] = asset.get("argument-hint") or ""
        meta["model"] = asset.get("model") or ""
    elif kind == "skill":
        meta["allowed-tools"] = normalized_list(asset.get("allowed-tools"))
    return meta


def asset_fingerprint(asset):
    payload = json.dumps(fingerprint_payload(asset), sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def asset_key(asset):
    return (asset["type"], asset["name"])


def native_record(ide, kind, rel):
    if kind == "unsupported-policy":
        return {
            "ide": ide, "kind": kind, "path": rel, "asset": None,
            "fingerprint": None, "error": "Codex execution policy",
        }
    asset = native_to_asset(ide, rel, kind)
    return {
        "ide": ide,
        "kind": asset["type"],
        "path": rel,
        "asset": asset,
        "fingerprint": asset_fingerprint(asset),
        "error": None,
    }


def canonical_indexes(assets):
    by_key, by_fp = {}, {}
    for asset in assets:
        by_key[asset_key(asset)] = asset
        by_fp[asset_fingerprint(asset)] = asset
    return by_key, by_fp


def analyze_native_state(staged_only=False):
    assets = load_assets()
    canonical_by_key, canonical_by_fp = canonical_indexes(assets)
    staged = staged_paths() if staged_only else None
    records, unsupported, parse_errors = [], [], []

    for ide, kind, rp in scan_native_files():
        if staged is not None and rp not in staged:
            continue
        if kind == "unsupported-policy":
            unsupported.append(
                "%s: Codex execution policy; keep Codex-only or document separately" % rp)
            continue
        if has_marker(rp):
            continue
        try:
            records.append(native_record(ide, kind, rp))
        except Exception as e:
            parse_errors.append("%s: could not parse native asset (%s)" % (rp, e))

    represented, canonical_conflicts = [], []
    without_canonical = {}
    for record in records:
        asset = record["asset"]
        key = asset_key(asset)
        if record["fingerprint"] in canonical_by_fp:
            represented.append(record)
        elif key in canonical_by_key:
            canonical_conflicts.append(
                "%s: canonical %s asset already exists with different content; resolve manually" %
                (record["path"], AI_REL))
        else:
            without_canonical.setdefault(key, []).append(record)

    exact_groups, native_only, duplicate_conflicts = [], [], []
    for key, group in sorted(without_canonical.items()):
        by_fp = {}
        for record in group:
            by_fp.setdefault(record["fingerprint"], []).append(record)
        if len(by_fp) > 1:
            paths = ", ".join(r["path"] for r in group)
            duplicate_conflicts.append(
                "%s %s: same name but different native content (%s)" %
                (key[0], key[1], paths))
            continue
        only_group = list(by_fp.values())[0]
        if len(only_group) > 1:
            exact_groups.append(only_group)
        else:
            native_only.append(only_group[0])

    possible = []
    by_body = {}
    for record in records:
        asset = record["asset"]
        body_key = (asset["type"], normalize_body(asset["body"]))
        by_body.setdefault(body_key, []).append(record)
    for (_kind, _body), group in sorted(by_body.items(), key=lambda item: item[0]):
        names = sorted(set(r["asset"]["name"] for r in group))
        if len(names) > 1:
            possible.append(
                "possible duplicate content with different names: %s" %
                ", ".join(r["path"] for r in group))

    return {
        "assets": assets,
        "canonical_by_key": canonical_by_key,
        "canonical_by_fp": canonical_by_fp,
        "records": records,
        "represented": represented,
        "canonical_conflicts": canonical_conflicts,
        "duplicate_conflicts": duplicate_conflicts,
        "exact_groups": exact_groups,
        "native_only": native_only,
        "possible": possible,
        "unsupported": unsupported,
        "parse_errors": parse_errors,
    }


def write_canonical_asset(asset):
    dest_rel = canonical_rel(asset)
    dest = abspath(dest_rel)
    content = render_canonical(asset)
    if os.path.exists(dest) and read_text(dest) != content:
        raise ValueError("canonical conflict at %s; resolve manually" % dest_rel)
    write_text(dest, content)
    if asset["type"] == "skill":
        copy_skill_aux(asset, os.path.dirname(dest))
    return dest_rel


def adopt_asset(ide, path):
    rel = relpath(path)
    kind = detect_native(ide, rel)
    if not kind:
        raise ValueError("%s is not a supported %s-native asset" % (rel, ide))
    if has_marker(rel):
        print("skip %s: already generated from %s/" % (rel, AI_REL))
        return 0
    asset = native_to_asset(ide, rel, kind)
    dest_rel = write_canonical_asset(asset)
    print("adopted %s -> %s" % (rel, dest_rel))
    return 0


def scan_native_files():
    found = []
    roots = [".cursor", ".windsurf", ".devin", ".agents", ".codex", ".claude", ".continue"]
    for root in roots:
        base = abspath(root)
        if not os.path.isdir(base):
            continue
        for dirpath, _dirs, files in os.walk(base):
            for f in files:
                rp = relpath(os.path.join(dirpath, f))
                ide = ide_from_path(rp)
                kind = detect_native(ide, rp) if ide else None
                if kind:
                    found.append((ide, kind, rp))
    return sorted(found, key=lambda x: x[2])


def command_adopt(args):
    try:
        if args.all:
            adopted = 0
            for ide, kind, rp in scan_native_files():
                if kind == "unsupported-policy" or has_marker(rp):
                    continue
                adopt_asset(ide, rp)
                adopted += 1
            print("adopted %d native assets" % adopted)
            return 0
        if not args.ide or not args.path:
            raise ValueError("usage: adopt <ide> <path> or adopt --all")
        return adopt_asset(args.ide, args.path)
    except ValueError as e:
        print("ERROR: %s" % e)
        return 1


def staged_paths():
    try:
        out = subprocess.check_output(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACMR"],
            cwd=REPO, universal_newlines=True)
    except Exception:
        return None
    return set(x.strip() for x in out.splitlines() if x.strip())


def find_doctor_issues(staged_only=False):
    assets = load_assets()
    texts, copies, managed, entries, degradations = build(assets)
    drift = compare_outputs(texts, copies, managed, entries)
    state = analyze_native_state(staged_only=staged_only)
    state["drift"] = drift
    state["degradations"] = degradations
    return state


def command_doctor(args):
    state = find_doctor_issues(args.staged)
    conflicts = state["canonical_conflicts"] + state["duplicate_conflicts"] + state["parse_errors"]
    has_blocking = any([
        state["drift"], state["native_only"], state["exact_groups"],
        conflicts, state["unsupported"],
    ])
    if not any([has_blocking, state["represented"], state["possible"], state["degradations"]]):
        print("Doctor found no agentic config issues.")
        return 0

    if state["exact_groups"]:
        print("Exact duplicate native groups:")
        for group in state["exact_groups"]:
            asset = group[0]["asset"]
            print("  %s %s:" % (asset["type"], asset["name"]))
            for record in group:
                print("    %s" % record["path"])
            print("    suggested: %s" % shell_command([
                COMMAND_NAME, "reconcile", asset["type"], asset["name"]]))
        print("  all exact groups: %s" %
              shell_command([COMMAND_NAME, "reconcile", "--all-exact"]))
    if state["represented"]:
        print("Native duplicates already represented in %s/:" % AI_REL)
        for record in state["represented"]:
            asset = record["asset"]
            print("  %s -> %s %s %s" %
                  (record["path"], AI_REL, asset["type"], asset["name"]))
        print("  optional cleanup: %s" %
              shell_command([COMMAND_NAME, "clean", "--native-duplicates"]))
    if state["native_only"]:
        print("Native-only assets:")
        for record in state["native_only"]:
            print("  %s: native-only, run %s" %
                  (record["path"], shell_command([
                      COMMAND_NAME, "adopt", record["ide"], record["path"]])))
    if state["drift"]:
        print("Generated but stale:")
        for item in state["drift"]:
            print("  %s" % item)
        print("  run %s" % shell_command([COMMAND_NAME]))
    if conflicts:
        print("Canonical conflicts:")
        for item in conflicts:
            print("  %s" % item)
    if state["possible"]:
        print("Possible duplicates:")
        for item in state["possible"]:
            print("  %s" % item)
    if state["unsupported"]:
        print("Unsupported or Codex-only assets:")
        for item in state["unsupported"]:
            print("  %s" % item)
    if state["degradations"] and not args.staged:
        print("Degraded mappings:")
        for item in state["degradations"]:
            print("  %s" % item)
    print_stealth_skips()
    return 1 if any([
        state["drift"], state["native_only"], state["exact_groups"],
        conflicts, state["unsupported"],
    ]) else 0


def reconcile_group(group):
    asset = group[0]["asset"]
    dest_rel = write_canonical_asset(asset)
    print("reconciled %s %s -> %s" %
          (asset["type"], asset["name"], dest_rel))
    for record in group:
        print("  source: %s" % record["path"])
    return dest_rel


def command_reconcile(args):
    try:
        state = analyze_native_state(staged_only=False)
        groups = state["exact_groups"]
        if args.all_exact:
            if not groups:
                print("No exact duplicate native groups to reconcile.")
                return 0
            for group in groups:
                reconcile_group(group)
            print("Reconciled %d exact duplicate groups." % len(groups))
            return 0

        if not args.kind or not args.name:
            print("ERROR: usage: reconcile <kind> <name> or reconcile --all-exact")
            return 1
        for group in groups:
            asset = group[0]["asset"]
            if asset["type"] == args.kind and asset["name"] == args.name:
                reconcile_group(group)
                return 0
        print("ERROR: no exact duplicate native group found for %s %s" %
              (args.kind, args.name))
        return 1
    except ValueError as e:
        print("ERROR: %s" % e)
        return 1


def remove_file_if_exists(path):
    if os.path.isfile(path):
        os.remove(path)
        return True
    return False


def remove_native_record(record):
    asset = record["asset"]
    removed = []
    if asset["type"] == "skill":
        root = os.path.dirname(abspath(record["path"]))
        skill_md = os.path.join(root, "SKILL.md")
        if remove_file_if_exists(skill_md):
            removed.append(relpath(skill_md))
        for rel in sorted(asset.get("aux", {})):
            aux_path = os.path.join(root, rel.replace("/", os.sep))
            if remove_file_if_exists(aux_path):
                removed.append(relpath(aux_path))
        prune_empty_dirs(removed)
    else:
        path = abspath(record["path"])
        if remove_file_if_exists(path):
            removed.append(record["path"])
            prune_empty_dirs([record["path"]])
    return removed


def command_clean(args):
    removed = []
    try:
        for entry in read_manifest_entries():
            if entry.get("mode", "file") != "file":
                continue
            p = entry.get("path")
            if not p or not p.startswith(GENERATED_PREFIXES):
                continue
            if os.path.exists(abspath(p)):
                assert_safe_file_mutation(p, entry, "clean")
            if remove_file_if_exists(abspath(p)):
                removed.append(p)
    except SafetyError as e:
        print("ERROR: %s" % e)
        return 1
    prune_empty_dirs(removed)

    native_removed = []
    if args.native_duplicates:
        state = analyze_native_state(staged_only=False)
        for record in state["represented"]:
            native_removed.extend(remove_native_record(record))

    print("Cleaned %d generated projection files." % len(removed))
    for p in removed:
        print("  removed %s" % p)
    if args.native_duplicates:
        print("Cleaned %d exact native duplicate files." % len(native_removed))
        for p in native_removed:
            print("  removed %s" % p)
    return 0


def command_bootstrap(_args):
    rc = command_sync(check=False)
    if rc:
        return rc
    print("")
    print("Bootstrap doctor report:")
    class DoctorArgs(object):
        staged = False
    doctor_rc = command_doctor(DoctorArgs())
    print("")
    if doctor_rc:
        print("Bootstrap generated local IDE projections, but doctor found follow-up work above.")
        print("Resolve the reported items, then rerun %s bootstrap." % COMMAND_NAME)
    else:
        print("Bootstrap complete. Your local IDE projections have been generated.")
        print("Generated IDE folders may be gitignored; edit %s/ or use adopt/reconcile." % AI_REL)
    return doctor_rc


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv == ["--check"]:
        return command_sync(check=True)
    if not argv:
        return command_sync(check=False)

    cmd = argv[0]
    if cmd == "sync":
        return command_sync(check=False)
    if cmd == "check":
        return command_sync(check=True)
    if cmd == "doctor":
        ap = argparse.ArgumentParser(prog="sync.py doctor")
        ap.add_argument("--staged", action="store_true")
        return command_doctor(ap.parse_args(argv[1:]))
    if cmd == "adopt":
        ap = argparse.ArgumentParser(prog="sync.py adopt")
        ap.add_argument("ide", nargs="?")
        ap.add_argument("path", nargs="?")
        ap.add_argument("--all", action="store_true")
        args = ap.parse_args(argv[1:])
        if args.ide == "--all":
            args.all = True
            args.ide = None
        return command_adopt(args)
    if cmd == "reconcile":
        ap = argparse.ArgumentParser(prog="sync.py reconcile")
        ap.add_argument("kind", nargs="?")
        ap.add_argument("name", nargs="?")
        ap.add_argument("--all-exact", action="store_true")
        return command_reconcile(ap.parse_args(argv[1:]))
    if cmd == "clean":
        ap = argparse.ArgumentParser(prog="sync.py clean")
        ap.add_argument("--native-duplicates", action="store_true")
        return command_clean(ap.parse_args(argv[1:]))
    if cmd == "bootstrap":
        ap = argparse.ArgumentParser(prog="sync.py bootstrap")
        return command_bootstrap(ap.parse_args(argv[1:]))

    print("ERROR: unknown command %s" % cmd)
    return 2


if __name__ == "__main__":
    sys.exit(main())
