#!/usr/bin/env python3
"""
sync.py - Bidirectional agentic config compiler.

The `.ai/` folder is the durable source of truth for a repo's shared
Agentic Config assets. Supported IDE-native files can also be used as
contribution surfaces: `adopt` imports them into `.ai/`, then `sync` exports
canonical equivalents for every supported IDE.

Usage:
    python3 .ai/sync.py                 # sync from .ai/
    python3 .ai/sync.py sync            # same
    python3 .ai/sync.py --check         # stale-output check, writes nothing
    python3 .ai/sync.py check           # same
    python3 .ai/sync.py doctor          # diagnose stale/native-only/degraded assets
    python3 .ai/sync.py adopt cursor .cursor/rules/foo.mdc
    python3 .ai/sync.py adopt --all
    python3 .ai/sync.py reconcile --all-exact
    python3 .ai/sync.py reconcile skill debug-word
    python3 .ai/sync.py demote cursor .cursor/commands/debug-word.md
    python3 .ai/sync.py promote cursor .cursor/commands/debug-word.md
    python3 .ai/sync.py clean --native-duplicates
    python3 .ai/sync.py bootstrap

Python 3.6+ stdlib only.
"""

import argparse
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_AI_DIR = HERE
DEFAULT_REPO = os.path.dirname(DEFAULT_AI_DIR)
REPO = os.path.abspath(os.environ.get("AGENTIC_CONFIG_REPO_ROOT") or DEFAULT_REPO)
AI_DIR = os.path.abspath(os.environ.get("AGENTIC_CONFIG_AI_DIR") or DEFAULT_AI_DIR)


def rel_from_repo(path):
    ap = os.path.abspath(path)
    try:
        return os.path.relpath(ap, REPO).replace(os.sep, "/")
    except ValueError:
        return path.replace(os.sep, "/")


AI_REL = rel_from_repo(AI_DIR)
MANIFEST = os.path.join(AI_DIR, ".manifest.json")
MANIFEST_REL = "%s/.manifest.json" % AI_REL
DEMOTIONS = os.path.join(AI_DIR, ".demotions.json")
DEMOTIONS_REL = "%s/.demotions.json" % AI_REL
COMMAND_NAME = os.environ.get("AGENTIC_CONFIG_COMMAND", "agentic")
STEALTH_MODE = os.environ.get("AGENTIC_CONFIG_STEALTH") == "1"
STEALTH_SKIPS = []
GENERATOR_LABEL = "agentic-config"
DEMOTIONS_VERSION = 1

TARGETS = ["claude", "cursor", "windsurf", "codex", "continue"]
KINDS = ["rule", "agent", "command", "skill"]
LIST_FIELDS = {
    "tools", "targets", "allowed-tools", "disallowed-tools", "globs",
    "paths", "arguments", "skills", "nickname_candidates",
}
BOOL_FIELDS = {
    "alwaysApply", "always_apply", "disable-model-invocation",
    "user-invocable", "invokable", "allow_implicit_invocation",
}
VALID_ACTIVATIONS = {"always_on", "model_decision", "glob", "manual"}

MARKER = "<!-- AUTOGENERATED from {src} by %s; do not edit. -->" % GENERATOR_LABEL
HASH_MARKER = "# AUTOGENERATED from {src} by %s; do not edit." % GENERATOR_LABEL
MANAGED_BEGIN = "<!-- BEGIN AGENTIC-CONFIG-KIT: {block} -->"
MANAGED_END = "<!-- END AGENTIC-CONFIG-KIT: {block} -->"
RULES_BLOCK = "rules"

SKILL_DIRS = {
    "claude": ".claude/skills",
    "cursor": ".cursor/skills",
    "windsurf": ".windsurf/skills",
    "codex": ".agents/skills",
}

GENERATED_PREFIXES = (
    ".claude/", ".cursor/", ".devin/", ".windsurf/",
    ".agents/", ".codex/agents/", ".continue/",
)
REPO_NATIVE_ROOTS = [
    ".cursor", ".windsurf", ".devin", ".agents", ".codex", ".claude", ".continue",
]
GLOBAL_NATIVE_ROOTS = [
    ("cursor", ".cursor/rules"),
    ("cursor", ".cursor/commands"),
    ("cursor", ".cursor/agents"),
    ("cursor", ".cursor/skills"),
    ("windsurf", ".windsurf/rules"),
    ("windsurf", ".windsurf/workflows"),
    ("windsurf", ".windsurf/skills"),
    ("windsurf", ".devin/rules"),
    ("codex", ".codex/skills"),
    ("codex", ".codex/agents"),
    ("codex", ".codex/rules"),
    ("claude", ".claude/rules"),
    ("claude", ".claude/commands"),
    ("claude", ".claude/agents"),
    ("claude", ".claude/skills"),
    ("continue", ".continue/prompts"),
]
IDE_NAME_PREFIXES = [
    "claude-code", "cursor", "codex", "claude", "windsurf", "devin", "continue",
]


class SafetyError(Exception):
    pass


class GlobalPriorityError(ValueError):
    pass


def relpath(path):
    return rel_from_repo(path)


def abspath(rel):
    return os.path.join(REPO, rel.replace("/", os.sep))


def is_relative_to(path, root):
    try:
        return os.path.commonpath([os.path.abspath(path), os.path.abspath(root)]) == os.path.abspath(root)
    except ValueError:
        return False


def display_path_for_abs(path):
    ap = os.path.abspath(path)
    if is_relative_to(ap, REPO):
        return rel_from_repo(ap)
    home = os.path.abspath(os.path.expanduser("~"))
    if is_relative_to(ap, home):
        return "~/%s" % os.path.relpath(ap, home).replace(os.sep, "/")
    return ap.replace(os.sep, "/")


def native_display_path(path):
    path = str(path)
    normalized = path.replace(os.sep, "/")
    if normalized.startswith("~/"):
        return display_path_for_abs(os.path.expanduser(path))
    expanded = os.path.expanduser(path)
    if os.path.isabs(expanded):
        return display_path_for_abs(expanded)
    return normalized


def native_abspath(path):
    path = str(path)
    expanded = os.path.expanduser(path)
    if os.path.isabs(expanded):
        return os.path.abspath(expanded)
    return abspath(path)


def normalize_repo_rel_path(path):
    path = str(path).strip().replace(os.sep, "/")
    if path.startswith("./"):
        path = path[2:]
    expanded = os.path.expanduser(path)
    if os.path.isabs(expanded):
        ap = os.path.abspath(expanded)
        if not is_relative_to(ap, REPO):
            raise ValueError("%s is outside this repo; demote repo generated paths only" % path)
        path = rel_from_repo(ap)
    path = path.replace(os.sep, "/")
    if path in ("", ".", "..") or path.startswith("../"):
        raise ValueError("%s is not a repo-relative generated path" % path)
    return path


def native_logical_path(path):
    path = native_display_path(path)
    if path.startswith("~/"):
        return path[2:]
    return path


def native_scope(path):
    return "global" if native_display_path(path).startswith("~/") else "repo"


def source_rel(*parts):
    return "/".join([AI_REL] + [p.strip("/") for p in parts if p])


def portable_asset_name(name):
    text = str(name or "")
    for prefix in IDE_NAME_PREFIXES:
        marker = "%s-" % prefix
        if text.startswith(marker) and len(text) > len(marker):
            return text[len(marker):]
    return text


def canonical_source_name(asset):
    parts = asset["srcrel"].split("/")
    if asset["type"] == "skill" and len(parts) >= 3:
        return parts[-2]
    leaf = parts[-1] if parts else asset["name"]
    return os.path.splitext(leaf)[0]


def canonical_ide_prefix_issues(assets):
    issues = []
    for asset in assets:
        name = asset["name"]
        source_name = canonical_source_name(asset)
        portable_name = portable_asset_name(name)
        portable_source = portable_asset_name(source_name)
        if portable_name == name and portable_source == source_name:
            continue
        neutral = portable_name if portable_name != name else portable_source
        issues.append(
            "%s: %s %s uses an IDE-specific name; rename source and frontmatter to %s" %
            (asset["srcrel"], asset["type"], name, neutral))
    return issues


def add_stealth_skip(message):
    if message not in STEALTH_SKIPS:
        STEALTH_SKIPS.append(message)


def shell_quote(value):
    return shlex.quote(str(value))


def shell_command(parts):
    return " ".join(shell_quote(p) for p in parts)


def read_text(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def write_text(path, content):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def read_bytes(path):
    with open(path, "rb") as f:
        return f.read()


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def sha256_text(text):
    return sha256_bytes(text.encode("utf-8"))


def write_bytes(path, data):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)


def strip_quotes(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def parse_bool(value):
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in ("1", "true", "yes", "on")


def split_list(value):
    if isinstance(value, list):
        return value
    value = strip_quotes(str(value).strip())
    if value.startswith("[") and value.endswith("]"):
        try:
            parsed = json.loads(value.replace("'", '"'))
            if isinstance(parsed, list):
                return [str(x).strip() for x in parsed if str(x).strip()]
        except Exception:
            value = value[1:-1]
    if "," in value:
        parts = value.split(",")
    else:
        parts = value.split()
    return [strip_quotes(x.strip()) for x in parts if strip_quotes(x.strip())]


def parse_frontmatter(text, src, require=True):
    """Lenient frontmatter parser for simple Markdown/YAML-ish files."""
    if not text.startswith("---\n"):
        if require:
            raise ValueError("%s: file must begin with '---' frontmatter" % src)
        return {}, text

    lines = text.split("\n")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        if require:
            raise ValueError("%s: frontmatter is not closed with '---'" % src)
        return {}, text

    fm = {}
    for ln in lines[1:end]:
        if not ln.strip() or ln.lstrip().startswith("#"):
            continue
        if ":" not in ln:
            if require:
                raise ValueError("%s: malformed frontmatter line: %r" % (src, ln))
            continue
        key, val = ln.split(":", 1)
        key, val = key.strip(), val.strip()
        if key in LIST_FIELDS:
            fm[key] = split_list(val)
        elif key in BOOL_FIELDS:
            fm[key] = parse_bool(val)
        else:
            fm[key] = strip_quotes(val)
    body = "\n".join(lines[end + 1:])
    return fm, body


def first_paragraph(text):
    cleaned = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith(MANAGED_BEGIN.split("{")[0]):
            if cleaned:
                break
            continue
        cleaned.append(line)
    return " ".join(cleaned)[:180]


def slugify(name):
    name = os.path.splitext(os.path.basename(name))[0]
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9._-]+", "-", name)
    name = re.sub(r"-+", "-", name).strip("-")
    return name or "unnamed"


def normalize_activation(value):
    value = (value or "model_decision").strip().lower().replace("-", "_")
    aliases = {
        "always": "always_on",
        "alwaysapply": "always_on",
        "always_apply": "always_on",
        "auto": "model_decision",
        "agent_requested": "model_decision",
        "intelligent": "model_decision",
        "apply_intelligently": "model_decision",
        "specific_files": "glob",
        "auto_attached": "glob",
    }
    value = aliases.get(value, value)
    if value not in VALID_ACTIVATIONS:
        raise ValueError("unsupported activation %r (expected one of %s)" %
                         (value, ", ".join(sorted(VALID_ACTIVATIONS))))
    return value


def yaml_scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    s = str(value)
    needs_quote = (
        s == ""
        or s != s.strip()
        or ": " in s
        or " #" in s
        or s.endswith(":")
        or s[0] in "\"'[]{}#&*!|>%@`?,"
        or (s[0] == "-" and (len(s) == 1 or s[1] == " "))
        or s.lower() in {"true", "false", "yes", "no", "on", "off", "null", "~"}
    )
    return json.dumps(s, ensure_ascii=False) if needs_quote else s


def render_frontmatter(pairs):
    out = ["---"]
    for key, value in pairs:
        if value is None or value == "" or value == []:
            continue
        if isinstance(value, list):
            value = ", ".join(value)
        out.append("%s: %s" % (key, yaml_scalar(value)))
    out.append("---")
    return "\n".join(out)


def render_markdown(pairs, body, srcrel, marker=True):
    chunks = [render_frontmatter(pairs)]
    if marker:
        chunks.append(MARKER.format(src=srcrel))
    chunks.append(body.rstrip("\n"))
    return "\n".join(chunks).rstrip("\n") + "\n"


def render_canonical(asset):
    kind = asset["type"]
    pairs = [("name", asset["name"]), ("description", asset["description"])]
    if kind == "rule":
        pairs.extend([
            ("activation", asset.get("activation")),
            ("globs", asset.get("globs")),
            ("targets", asset.get("targets")),
        ])
    elif kind == "agent":
        pairs.extend([
            ("tools", asset.get("tools")),
            ("model", asset.get("model")),
            ("targets", asset.get("targets")),
        ])
    elif kind == "command":
        pairs.extend([
            ("argument-hint", asset.get("argument-hint")),
            ("model", asset.get("model")),
            ("targets", asset.get("targets")),
        ])
    elif kind == "skill":
        pairs.extend([
            ("allowed-tools", asset.get("allowed-tools")),
            ("targets", asset.get("targets")),
        ])
    return render_markdown(pairs, asset["body"], asset["srcrel"], marker=False)


def toml_string(value):
    return json.dumps(value or "", ensure_ascii=False)


def render_codex_agent(asset, name=None):
    name = name or asset["name"]
    lines = [
        'name = %s' % toml_string(name),
        'description = %s' % toml_string(asset["description"]),
        'developer_instructions = %s' % toml_string(asset["body"].rstrip("\n")),
    ]
    if asset.get("model"):
        lines.append('model = %s' % toml_string(asset["model"]))
    return HASH_MARKER.format(src=asset["srcrel"]) + "\n" + "\n".join(lines) + "\n"


def render_codex_openai_yaml(display_name, short_description, implicit):
    body = [
        "interface:",
        "  display_name: %s" % yaml_scalar(display_name),
        "  short_description: %s" % yaml_scalar(short_description),
        "policy:",
        "  allow_implicit_invocation: %s" % ("true" if implicit else "false"),
        "",
    ]
    return "\n".join(body)


def codex_command_display_name(name):
    return "⚡ /%s" % name


def base_asset(kind, name, description, body, srcrel, fm=None, srcdir=None):
    fm = fm or {}
    asset = {
        "type": kind,
        "name": fm.get("name") or name,
        "description": description,
        "body": body,
        "srcrel": srcrel,
        "targets": fm.get("targets"),
        "tools": fm.get("tools"),
        "model": fm.get("model"),
        "argument-hint": fm.get("argument-hint"),
        "allowed-tools": fm.get("allowed-tools"),
        "disallowed-tools": fm.get("disallowed-tools"),
        "activation": normalize_activation(fm.get("activation") or fm.get("trigger")),
        "globs": fm.get("globs") or fm.get("paths"),
        "aux": {},
    }
    if kind != "rule":
        asset["activation"] = None
        asset["globs"] = None
    if srcdir is not None:
        for root, _dirs, files in os.walk(srcdir):
            for f in files:
                if root == srcdir and f == "SKILL.md":
                    continue
                if f == ".DS_Store":
                    continue
                ap = os.path.join(root, f)
                rel = os.path.relpath(ap, srcdir).replace(os.sep, "/")
                asset["aux"][rel] = ap
    return asset


def load_markdown_asset(kind, name, path, srcrel, srcdir=None):
    text = read_text(path)
    fm, body = parse_frontmatter(text, srcrel, require=True)
    description = fm.get("description")
    if not description:
        raise ValueError("%s: missing required 'description'" % srcrel)
    return base_asset(kind, name, description, body, srcrel, fm=fm, srcdir=srcdir)


def load_assets():
    assets = []

    rdir = os.path.join(AI_DIR, "rules")
    for f in sorted(os.listdir(rdir)) if os.path.isdir(rdir) else []:
        if f.endswith(".md"):
            assets.append(load_markdown_asset(
                "rule", f[:-3], os.path.join(rdir, f), source_rel("rules", f)))

    adir = os.path.join(AI_DIR, "agents")
    for f in sorted(os.listdir(adir)) if os.path.isdir(adir) else []:
        if f.endswith(".md"):
            assets.append(load_markdown_asset(
                "agent", f[:-3], os.path.join(adir, f), source_rel("agents", f)))

    cdir = os.path.join(AI_DIR, "commands")
    for f in sorted(os.listdir(cdir)) if os.path.isdir(cdir) else []:
        if f.endswith(".md"):
            assets.append(load_markdown_asset(
                "command", f[:-3], os.path.join(cdir, f), source_rel("commands", f)))

    sdir = os.path.join(AI_DIR, "skills")
    for d in sorted(os.listdir(sdir)) if os.path.isdir(sdir) else []:
        skill_md = os.path.join(sdir, d, "SKILL.md")
        if os.path.isfile(skill_md):
            assets.append(load_markdown_asset(
                "skill", d, skill_md, source_rel("skills", d, "SKILL.md"),
                srcdir=os.path.join(sdir, d)))

    assets.sort(key=lambda a: (a["type"], a["name"]))
    return assets


def target_allowed(asset, target):
    targets = asset.get("targets")
    return not targets or target in targets


def skill_pairs(asset, name=None, description=None, explicit_only=False):
    return [
        ("name", name or asset["name"]),
        ("description", description or asset["description"]),
        ("allowed-tools", asset.get("allowed-tools")),
        ("disable-model-invocation", True if explicit_only else None),
    ]


def rule_skill_body(asset, name=None):
    name = name or asset["name"]
    lines = [
        "# Rule: %s" % name,
        "",
        "Activation: %s" % asset.get("activation", "model_decision"),
    ]
    if asset.get("globs"):
        lines.append("Globs: %s" % ", ".join(asset["globs"]))
    lines.extend(["", asset["body"].rstrip("\n")])
    return "\n".join(lines).rstrip("\n") + "\n"


def rule_managed_block(rules):
    if not rules:
        return ""
    parts = [
        "# Agentic Config Rules",
        "",
        "This section is generated from `%s/rules/` by `%s`." % (AI_REL, GENERATOR_LABEL),
        "Edit canonical rules in `%s/rules/`, not here." % AI_REL,
        "",
    ]
    for asset in rules:
        name = portable_asset_name(asset["name"])
        parts.append("## %s" % name)
        parts.append("")
        parts.append("- Description: %s" % asset["description"])
        parts.append("- Activation: %s" % asset.get("activation", "model_decision"))
        if asset.get("globs"):
            parts.append("- Globs: %s" % ", ".join(asset["globs"]))
        parts.append("")
        parts.append(asset["body"].rstrip("\n"))
        parts.append("")
    return "\n".join(parts).rstrip("\n") + "\n"


def outputs_for(asset, target):
    t, source_name, desc, body, src = (
        asset["type"], asset["name"], asset["description"],
        asset["body"], asset["srcrel"])
    n = portable_asset_name(source_name)
    texts, copies, degradations = {}, {}, []

    if t == "rule":
        activation = asset.get("activation") or "model_decision"
        globs = asset.get("globs")
        if target == "claude":
            pairs = [("name", n), ("description", desc),
                     ("activation", activation), ("paths", globs)]
            texts[".claude/rules/%s.md" % n] = render_markdown(pairs, body, src)
        elif target == "cursor":
            always = activation == "always_on"
            pairs = [("description", desc if activation == "model_decision" else desc),
                     ("globs", globs if activation == "glob" else None),
                     ("alwaysApply", always)]
            texts[".cursor/rules/%s.mdc" % n] = render_markdown(pairs, body, src)
        elif target == "windsurf":
            pairs = [("trigger", activation), ("description", desc),
                     ("globs", globs if activation == "glob" else None)]
            texts[".devin/rules/%s.md" % n] = render_markdown(pairs, body, src)
        elif target == "codex":
            if activation != "always_on":
                dn = "rule-%s" % n
                skill_body = rule_skill_body(asset, n)
                texts[".agents/skills/%s/SKILL.md" % dn] = render_markdown(
                    [("name", dn), ("description", desc),
                     ("disable-model-invocation", activation == "manual")],
                    skill_body, src)
                texts[".agents/skills/%s/agents/openai.yaml" % dn] = (
                    HASH_MARKER.format(src=src) + "\n" +
                    render_codex_openai_yaml("Rule: %s" % n, desc,
                                             activation != "manual"))
            degradations.append("codex: rule %s also appears in managed AGENTS.md" % n)
        elif target == "continue":
            dn = "rule-%s" % n
            texts[".continue/prompts/%s.md" % dn] = render_markdown(
                [("name", dn), ("description", desc), ("invokable", True)],
                rule_skill_body(asset, n), src)
            degradations.append("continue: rule %s is available as a prompt" % n)

    elif t == "agent":
        if target == "claude":
            pairs = [("name", n), ("description", desc),
                     ("tools", asset.get("tools")), ("model", asset.get("model"))]
            texts[".claude/agents/%s.md" % n] = render_markdown(pairs, body, src)
        elif target == "cursor":
            texts[".cursor/agents/%s.md" % n] = render_markdown(
                [("name", n), ("description", desc)], body, src)
        elif target == "windsurf":
            dn = "agent-%s" % n
            texts[".windsurf/skills/%s/SKILL.md" % dn] = render_markdown(
                [("name", dn), ("description", desc)], body, src)
            degradations.append("windsurf: agent %s is exported as a skill" % n)
        elif target == "codex":
            texts[".codex/agents/%s.toml" % n] = render_codex_agent(asset, n)
        elif target == "continue":
            dn = "agent-%s" % n
            texts[".continue/prompts/%s.md" % dn] = render_markdown(
                [("name", dn), ("description", desc), ("invokable", True)],
                body, src)
            degradations.append("continue: agent %s is exported as a prompt" % n)

    elif t == "command":
        if target == "claude":
            texts[".claude/commands/%s.md" % n] = render_markdown(
                [("description", desc), ("argument-hint", asset.get("argument-hint")),
                 ("model", asset.get("model"))], body, src)
            texts[".claude/skills/%s/SKILL.md" % n] = render_markdown(
                [("name", n), ("description", desc),
                 ("argument-hint", asset.get("argument-hint")),
                 ("disable-model-invocation", True)], body, src)
        elif target == "cursor":
            texts[".cursor/commands/%s.md" % n] = render_markdown(
                [("description", desc), ("argument-hint", asset.get("argument-hint"))],
                body, src)
        elif target == "windsurf":
            texts[".windsurf/workflows/%s.md" % n] = render_markdown(
                [("name", n), ("description", desc)], body, src)
        elif target == "codex":
            dn = "command-%s" % n
            texts[".agents/skills/%s/SKILL.md" % dn] = render_markdown(
                [("name", dn), ("description", desc),
                 ("argument-hint", asset.get("argument-hint")),
                 ("disable-model-invocation", True)], body, src)
            texts[".agents/skills/%s/agents/openai.yaml" % dn] = (
                HASH_MARKER.format(src=src) + "\n" +
                render_codex_openai_yaml(codex_command_display_name(n), desc, False))
            degradations.append("codex: command %s is exported as an explicit skill" % n)
        elif target == "continue":
            texts[".continue/prompts/%s.md" % n] = render_markdown(
                [("name", n), ("description", desc), ("invokable", True)],
                body, src)

    elif t == "skill":
        if target in SKILL_DIRS:
            base = "%s/%s" % (SKILL_DIRS[target], n)
            texts["%s/SKILL.md" % base] = render_markdown(
                [("name", n), ("description", desc),
                 ("allowed-tools", asset.get("allowed-tools"))], body, src)
            for rel, ap in asset["aux"].items():
                copies["%s/%s" % (base, rel)] = ap
        elif target == "continue":
            texts[".continue/prompts/%s.md" % n] = render_markdown(
                [("name", n), ("description", desc), ("invokable", True)],
                body, src)
            degradations.append("continue: skill %s is exported as a prompt" % n)

    return texts, copies, degradations


def manifest_entry(path, source, kind, target, mode="file", block=None, content_hash=None):
    entry = {
        "path": path,
        "source": source,
        "kind": kind,
        "target": target,
        "mode": mode,
    }
    if block:
        entry["block"] = block
    if content_hash:
        entry["hash"] = content_hash
    return entry


def git_tracked_paths():
    try:
        out = subprocess.check_output(
            ["git", "ls-files", "-z"], cwd=REPO, stderr=subprocess.DEVNULL)
    except Exception:
        return set()
    return set(p for p in out.decode("utf-8").split("\0") if p)


def filter_stealth_tracked_outputs(texts, copies, managed, entries):
    if not STEALTH_MODE:
        return
    tracked = git_tracked_paths()
    if not tracked:
        return

    skipped_paths = set()
    for p in sorted(list(texts.keys())):
        if p in tracked:
            skipped_paths.add(p)
            del texts[p]
            add_stealth_skip(
                "%s is tracked; stealth mode skipped generated output for this path." % p)
    for p in sorted(list(copies.keys())):
        if p in tracked:
            skipped_paths.add(p)
            del copies[p]
            add_stealth_skip(
                "%s is tracked; stealth mode skipped generated output for this path." % p)
    for p in sorted(list(managed.keys())):
        if p in tracked:
            skipped_paths.add(p)
            del managed[p]
            if p == "AGENTS.md":
                add_stealth_skip(
                    "AGENTS.md is tracked; stealth mode skipped Codex managed rules "
                    "for this file. Use normal init or manual adoption for full Codex fidelity.")
            else:
                add_stealth_skip(
                    "%s is tracked; stealth mode skipped managed output for this path." % p)

    if skipped_paths:
        entries[:] = [
            e for e in entries
            if e.get("path") not in skipped_paths
        ]


def read_demotions():
    if not os.path.isfile(DEMOTIONS):
        return []
    try:
        data = json.load(open(DEMOTIONS, encoding="utf-8"))
    except Exception as e:
        raise SystemExit("ERROR: could not read %s (%s)" % (DEMOTIONS_REL, e))
    if not isinstance(data, dict):
        raise SystemExit("ERROR: %s must contain a JSON object" % DEMOTIONS_REL)
    records = data.get("demotions", [])
    if not isinstance(records, list):
        raise SystemExit("ERROR: %s demotions must be a list" % DEMOTIONS_REL)
    normalized = []
    seen = set()
    for record in records:
        if not isinstance(record, dict):
            raise SystemExit("ERROR: %s contains a non-object demotion" % DEMOTIONS_REL)
        consumer = record.get("consumer")
        path = record.get("path")
        if consumer not in TARGETS or not path:
            raise SystemExit("ERROR: %s contains an invalid demotion" % DEMOTIONS_REL)
        item = dict(record)
        item["path"] = normalize_repo_rel_path(path)
        key = (consumer, item["path"])
        if key in seen:
            continue
        seen.add(key)
        normalized.append(item)
    return sorted(normalized, key=lambda x: (x.get("consumer"), x.get("path")))


def write_demotions(records):
    records = sorted(records, key=lambda x: (x.get("consumer"), x.get("path")))
    if not records:
        if os.path.isfile(DEMOTIONS):
            os.remove(DEMOTIONS)
        return
    content = json.dumps(
        {"version": DEMOTIONS_VERSION, "demotions": records},
        indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    write_text(DEMOTIONS, content)


def generated_output_group(path, entries):
    path = normalize_repo_rel_path(path)
    primary = None
    for entry in entries:
        if entry.get("mode", "file") == "file" and entry.get("path") == path:
            primary = entry
            break
    if not primary:
        return []

    group = [primary]
    if path.endswith("/SKILL.md"):
        base = path[:-len("/SKILL.md")]
        group = [
            entry for entry in entries
            if entry.get("mode", "file") == "file"
            and entry.get("source") == primary.get("source")
            and entry.get("target") == primary.get("target")
            and entry.get("kind") == primary.get("kind")
            and (entry.get("path") == path or entry.get("path", "").startswith(base + "/"))
        ]
    return sorted(group, key=lambda x: x.get("path"))


def apply_demotions(texts, copies, entries):
    demotions = read_demotions()
    if not demotions:
        return
    suppressed = set()
    for record in demotions:
        group = generated_output_group(record["path"], entries)
        if group:
            suppressed.update(entry["path"] for entry in group)
        else:
            suppressed.update(record.get("group") or [record["path"]])
    for path in suppressed:
        texts.pop(path, None)
        copies.pop(path, None)
    entries[:] = [
        entry for entry in entries
        if entry.get("path") not in suppressed
    ]


def build(assets, apply_saved_demotions=True):
    names = {}
    for asset in assets:
        key = asset["name"]
        if key in names:
            raise SystemExit(
                "ERROR: duplicate asset name '%s' (%s and %s). Names must be "
                "unique across rules, agents, commands, and skills." %
                (key, names[key], asset["type"]))
        names[key] = asset["type"]

    texts, copies, entries, degradations = {}, {}, [], []

    def claim(path, where):
        if path in texts or path in copies:
            raise SystemExit("ERROR: output collision at '%s' (from %s)." %
                             (path, where))

    for asset in assets:
        for target in TARGETS:
            if not target_allowed(asset, target):
                continue
            ot, oc, od = outputs_for(asset, target)
            for p, content in sorted(ot.items()):
                claim(p, asset["srcrel"])
                texts[p] = content
                entries.append(manifest_entry(
                    p, asset["srcrel"], asset["type"], target,
                    content_hash=sha256_text(content)))
            for p, src in sorted(oc.items()):
                claim(p, asset["srcrel"])
                copies[p] = src
                entries.append(manifest_entry(
                    p, asset["srcrel"], asset["type"], target,
                    content_hash=sha256_bytes(read_bytes(src))))
            degradations.extend(od)

    codex_rules = [
        a for a in assets
        if a["type"] == "rule" and target_allowed(a, "codex")
    ]
    managed = {}
    if codex_rules:
        managed["AGENTS.md"] = {RULES_BLOCK: rule_managed_block(codex_rules)}
        entries.append(manifest_entry(
            "AGENTS.md", source_rel("rules"), "rule", "codex",
            mode="managed-block", block=RULES_BLOCK))

    if apply_saved_demotions:
        apply_demotions(texts, copies, entries)
    filter_stealth_tracked_outputs(texts, copies, managed, entries)
    entries.sort(key=lambda e: (e["path"], e.get("block", ""), e["source"]))
    return texts, copies, managed, entries, sorted(set(degradations))


def read_manifest_entries():
    if not os.path.isfile(MANIFEST):
        return []
    try:
        data = json.load(open(MANIFEST, encoding="utf-8"))
    except Exception:
        return []
    outputs = data.get("outputs", [])
    entries = []
    for item in outputs:
        if isinstance(item, str):
            entries.append(manifest_entry(item, "", "", "", mode="file"))
        elif isinstance(item, dict) and item.get("path"):
            entries.append(item)
    return entries


def manifest_content(entries):
    return json.dumps({"version": 2, "outputs": entries},
                      indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def managed_block_text(block, content):
    return (MANAGED_BEGIN.format(block=block) + "\n" +
            MARKER.format(src=source_rel("rules")) + "\n\n" +
            content.rstrip("\n") + "\n" +
            MANAGED_END.format(block=block) + "\n")


def apply_managed_block(existing, block, content):
    begin = MANAGED_BEGIN.format(block=block)
    end = MANAGED_END.format(block=block)
    pattern = re.compile(
        r"\n?%s\n.*?\n%s\n?" % (re.escape(begin), re.escape(end)),
        re.DOTALL)
    replacement = managed_block_text(block, content) if content else ""
    if pattern.search(existing):
        def repl(match):
            if not replacement:
                return "\n" if match.group(0).startswith("\n") else ""
            prefix = "\n" if match.group(0).startswith("\n") else ""
            return prefix + replacement
        updated = pattern.sub(repl, existing)
    elif replacement:
        sep = "\n\n" if existing.rstrip("\n") else ""
        updated = existing.rstrip("\n") + sep + replacement
    else:
        updated = existing
    return re.sub(r"\n{4,}", "\n\n\n", updated).rstrip("\n") + ("\n" if updated else "")


def expected_managed_content(path, blocks):
    ap = abspath(path)
    existing = read_text(ap) if os.path.isfile(ap) else ""
    updated = existing
    for block, content in sorted(blocks.items()):
        updated = apply_managed_block(updated, block, content)
    return updated


def prune_empty_dirs(rel_paths, boundary=None):
    boundary = os.path.abspath(boundary or REPO)
    for rp in rel_paths:
        d = os.path.dirname(native_abspath(rp))
        while is_relative_to(d, boundary) and d != boundary and os.path.isdir(d):
            if os.listdir(d):
                break
            os.rmdir(d)
            d = os.path.dirname(d)


def manifest_files_by_path(entries):
    by_path = {}
    for entry in entries:
        if entry.get("mode", "file") == "file" and entry.get("path"):
            by_path[entry["path"]] = entry
    return by_path


def existing_matches_manifest_hash(rel, entry):
    if not entry or not entry.get("hash"):
        return False
    ap = abspath(rel)
    if not os.path.isfile(ap):
        return False
    return sha256_bytes(read_bytes(ap)) == entry.get("hash")


def assert_safe_file_mutation(rel, old_entry, action, represented=None):
    ap = abspath(rel)
    if not os.path.exists(ap):
        return
    if not os.path.isfile(ap):
        raise SafetyError(
            "refusing to %s %s because that path exists and is not a file" %
            (action, rel))
    if has_marker(rel) or existing_matches_manifest_hash(rel, old_entry):
        return
    # A markerless native whose content is already captured verbatim in `.ai/`
    # (an adopted source surface) is safe to refresh in place: the projection we
    # write is the canonical truth, so nothing is lost. Divergent or unrelated
    # markerless files are never in `represented`, so they stay protected.
    if represented and rel in represented:
        return
    raise SafetyError(
        "refusing to %s markerless file at generated path %s. "
        "Run %s status and resolve the Blocking item before syncing." %
        (action, rel, COMMAND_NAME))


def preflight_file_mutations(texts, copies, old_entries, new_file_paths, represented=None):
    old_files = manifest_files_by_path(old_entries)
    tracked = git_tracked_paths() if STEALTH_MODE else set()
    for p, content in sorted(texts.items()):
        ap = abspath(p)
        if os.path.isfile(ap) and read_text(ap) == content:
            continue
        assert_safe_file_mutation(p, old_files.get(p), "overwrite", represented)
    for p, src in sorted(copies.items()):
        ap = abspath(p)
        if os.path.isfile(ap) and read_bytes(ap) == read_bytes(src):
            continue
        assert_safe_file_mutation(p, old_files.get(p), "overwrite", represented)
    for entry in old_entries:
        if entry.get("mode", "file") != "file":
            continue
        p = entry.get("path")
        if p and p not in new_file_paths and os.path.exists(abspath(p)):
            if STEALTH_MODE and p in tracked:
                add_stealth_skip(
                    "%s is tracked; stealth mode skipped pruning stale generated output." % p)
                continue
            assert_safe_file_mutation(p, entry, "prune", represented)
    return old_files


def compare_outputs(texts, copies, managed, entries):
    drift = []
    tracked = git_tracked_paths() if STEALTH_MODE else set()
    for p, content in sorted(texts.items()):
        ap = abspath(p)
        if not os.path.isfile(ap) or read_text(ap) != content:
            drift.append(p)
    for p, src in sorted(copies.items()):
        ap = abspath(p)
        if not os.path.isfile(ap) or read_bytes(ap) != read_bytes(src):
            drift.append(p)
    for p, blocks in sorted(managed.items()):
        ap = abspath(p)
        expected = expected_managed_content(p, blocks)
        if not os.path.isfile(ap) or read_text(ap) != expected:
            drift.append("%s (managed block)" % p)

    old_entries = read_manifest_entries()
    new_file_paths = set(list(texts.keys()) + list(copies.keys()))
    new_managed = set((p, b) for p, blocks in managed.items() for b in blocks)
    for entry in old_entries:
        mode = entry.get("mode", "file")
        p = entry.get("path")
        if mode == "managed-block":
            key = (p, entry.get("block"))
            if key not in new_managed and os.path.isfile(abspath(p)):
                if STEALTH_MODE and p in tracked:
                    add_stealth_skip(
                        "%s is tracked; stealth mode skipped pruning stale managed output." % p)
                    continue
                existing = read_text(abspath(p))
                begin = MANAGED_BEGIN.format(block=entry.get("block"))
                if begin in existing:
                    drift.append("%s (stale managed block)" % p)
        elif p and p not in new_file_paths and os.path.exists(abspath(p)):
            if STEALTH_MODE and p in tracked:
                add_stealth_skip(
                    "%s is tracked; stealth mode skipped pruning stale generated output." % p)
                continue
            drift.append("%s (stale; should be pruned)" % p)

    cur_manifest = read_text(MANIFEST) if os.path.isfile(MANIFEST) else ""
    new_manifest = manifest_content(entries)
    if cur_manifest != new_manifest:
        drift.append(MANIFEST_REL)
    return drift


def write_outputs(texts, copies, managed, entries, represented=None):
    old_entries = read_manifest_entries()
    tracked = git_tracked_paths() if STEALTH_MODE else set()
    new_file_paths = set(list(texts.keys()) + list(copies.keys()))
    new_managed = set((p, b) for p, blocks in managed.items() for b in blocks)
    old_files = preflight_file_mutations(
        texts, copies, old_entries, new_file_paths, represented)
    created = updated = 0

    for p, content in sorted(texts.items()):
        ap = abspath(p)
        if os.path.isfile(ap) and read_text(ap) == content:
            continue
        assert_safe_file_mutation(p, old_files.get(p), "overwrite", represented)
        existed = os.path.exists(ap)
        write_text(ap, content)
        created += 0 if existed else 1
        updated += 1 if existed else 0

    for p, src in sorted(copies.items()):
        ap = abspath(p)
        data = read_bytes(src)
        if os.path.isfile(ap) and read_bytes(ap) == data:
            continue
        assert_safe_file_mutation(p, old_files.get(p), "overwrite", represented)
        existed = os.path.exists(ap)
        write_bytes(ap, data)
        created += 0 if existed else 1
        updated += 1 if existed else 0

    managed_updated = 0
    for p, blocks in sorted(managed.items()):
        ap = abspath(p)
        expected = expected_managed_content(p, blocks)
        if os.path.isfile(ap) and read_text(ap) == expected:
            continue
        write_text(ap, expected)
        managed_updated += 1

    pruned = []
    for entry in old_entries:
        mode = entry.get("mode", "file")
        p = entry.get("path")
        if not p:
            continue
        if mode == "managed-block":
            block = entry.get("block")
            if (p, block) not in new_managed and os.path.isfile(abspath(p)):
                if STEALTH_MODE and p in tracked:
                    add_stealth_skip(
                        "%s is tracked; stealth mode skipped pruning stale managed output." % p)
                    continue
                existing = read_text(abspath(p))
                updated_content = apply_managed_block(existing, block, "")
                if updated_content != existing:
                    write_text(abspath(p), updated_content)
                    pruned.append("%s (%s block)" % (p, block))
        elif p not in new_file_paths and os.path.exists(abspath(p)):
            if STEALTH_MODE and p in tracked:
                add_stealth_skip(
                    "%s is tracked; stealth mode skipped pruning stale generated output." % p)
                continue
            assert_safe_file_mutation(p, entry, "prune", represented)
            os.remove(abspath(p))
            pruned.append(p)
    prune_empty_dirs([p.split(" (", 1)[0] for p in pruned])

    new_manifest = manifest_content(entries)
    if not os.path.isfile(MANIFEST) or read_text(MANIFEST) != new_manifest:
        write_text(MANIFEST, new_manifest)

    return created, updated, managed_updated, pruned


def print_stealth_skips():
    if not STEALTH_SKIPS:
        return
    print("Stealth skipped tracked outputs:")
    for item in STEALTH_SKIPS:
        print("  %s" % item)


def command_sync(check=False):
    assets = load_assets()
    texts, copies, managed, entries, _degradations = build(assets)
    if check:
        drift = compare_outputs(texts, copies, managed, entries)
        if drift:
            print("Generated IDE folders are STALE vs %s master:" % AI_REL)
            for d in drift:
                print("    %s" % d)
            print("\nRun %s sync to regenerate local projections and refresh the manifest." % COMMAND_NAME)
            print("If sync is blocked, run %s status and resolve the Blocking items first." % COMMAND_NAME)
            print_stealth_skips()
            return 1
        print("In sync: %d generated entries match %s master." % (len(entries), AI_REL))
        print_stealth_skips()
        return 0

    represented = represented_native_paths(assets)
    try:
        created, updated, managed_updated, pruned = write_outputs(
            texts, copies, managed, entries, represented)
    except SafetyError as e:
        print("ERROR: %s" % e)
        print("")
        print("Sync is blocked by a markerless native file that Agentic Config will not overwrite.")
        print("Run %s status to see blocking items and the next safe step." % COMMAND_NAME)
        return 1
    by_type = {}
    for asset in assets:
        by_type[asset["type"]] = by_type.get(asset["type"], 0) + 1
    summary = ", ".join("%d %ss" % (by_type[k], k) for k in sorted(by_type))
    print("Synced %d canonical assets (%s) -> %d manifest entries across %d IDEs." %
          (len(assets), summary, len(entries), len(TARGETS)))
    print("  created %d, updated %d, managed %d, pruned %d." %
          (created, updated, managed_updated, len(pruned)))
    for p in pruned:
        print("  pruned %s" % p)
    print_stealth_skips()
    return 0


def has_marker(rel):
    ap = native_abspath(rel)
    if not os.path.isfile(ap):
        return False
    try:
        return "AUTOGENERATED from" in read_text(ap)
    except UnicodeDecodeError:
        return False


def detect_native(ide, rel):
    rel = native_logical_path(rel)
    if ide == "cursor":
        if rel.startswith(".cursor/rules/") and rel.endswith(".mdc"):
            return "rule"
        if rel.startswith(".cursor/commands/") and rel.endswith(".md"):
            return "command"
        if rel.startswith(".cursor/agents/") and rel.endswith(".md"):
            return "agent"
        if rel.startswith(".cursor/skills/") and rel.endswith("/SKILL.md"):
            return "skill"
    if ide == "windsurf":
        if (rel.startswith(".devin/rules/") or rel.startswith(".windsurf/rules/")) and rel.endswith(".md"):
            return "rule"
        if rel.startswith(".windsurf/workflows/") and rel.endswith(".md"):
            return "command"
        if rel.startswith(".windsurf/skills/") and rel.endswith("/SKILL.md"):
            return "skill"
    if ide == "codex":
        if rel.startswith(".codex/rules/") and rel.endswith(".rules"):
            return "unsupported-policy"
        if rel.startswith(".agents/skills/") and rel.endswith("/SKILL.md"):
            return "skill"
        if rel.startswith(".codex/skills/") and rel.endswith("/SKILL.md"):
            return "skill"
        if rel.startswith(".codex/agents/") and rel.endswith(".toml"):
            return "agent"
    if ide == "claude":
        if rel.startswith(".claude/rules/") and rel.endswith(".md"):
            return "rule"
        if rel.startswith(".claude/commands/") and rel.endswith(".md"):
            return "command"
        if rel.startswith(".claude/agents/") and rel.endswith(".md"):
            return "agent"
        if rel.startswith(".claude/skills/") and rel.endswith("/SKILL.md"):
            return "skill"
    if ide == "continue":
        if rel.startswith(".continue/prompts/") and rel.endswith(".md"):
            return "command"
    return None


def ide_from_path(rel):
    rel = native_logical_path(rel)
    if rel.startswith(".cursor/"):
        return "cursor"
    if rel.startswith(".windsurf/") or rel.startswith(".devin/"):
        return "windsurf"
    if rel.startswith(".agents/") or rel.startswith(".codex/"):
        return "codex"
    if rel.startswith(".claude/"):
        return "claude"
    if rel.startswith(".continue/"):
        return "continue"
    return None


def native_name(kind, rel):
    rel = native_logical_path(rel)
    parts = rel.split("/")
    if kind == "skill":
        return parts[-2]
    if kind == "agent" and rel.endswith(".toml"):
        return slugify(parts[-1])
    return slugify(parts[-1])


def strip_marker(body):
    lines = body.splitlines()
    lines = [ln for ln in lines if "AUTOGENERATED from" not in ln]
    return "\n".join(lines).strip("\n") + "\n"


def parse_simple_toml_agent(text, src):
    values = {}
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        i += 1
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, val = line.split("=", 1)
        key, val = key.strip(), val.strip()
        if val.startswith('"""'):
            collected = [val[3:]]
            while i < len(lines) and not collected[-1].endswith('"""'):
                collected.append(lines[i])
                i += 1
            joined = "\n".join(collected)
            if joined.endswith('"""'):
                joined = joined[:-3]
            values[key] = joined
        else:
            try:
                values[key] = json.loads(val)
            except Exception:
                values[key] = strip_quotes(val)
    body = values.get("developer_instructions") or values.get("prompt") or ""
    desc = values.get("description") or first_paragraph(body) or "Imported Codex agent."
    name = portable_asset_name(values.get("name") or slugify(src))
    fm = {"name": name, "description": desc, "model": values.get("model")}
    return base_asset("agent", name, desc, body, src, fm=fm)


def cursor_activation(fm):
    if parse_bool(fm.get("alwaysApply", False)):
        return "always_on"
    if fm.get("globs"):
        return "glob"
    if fm.get("description"):
        return "model_decision"
    return "manual"


def native_to_asset(ide, rel, kind):
    rel = native_display_path(rel)
    ap = native_abspath(rel)
    text = read_text(ap)
    if kind == "unsupported-policy":
        raise ValueError("%s is a Codex execution policy, not portable behavioral guidance" % rel)
    if kind == "agent" and ide == "codex" and rel.endswith(".toml"):
        return parse_simple_toml_agent(text, rel)

    fm, body = parse_frontmatter(text, rel, require=False)
    fm = dict(fm)
    body = strip_marker(body)
    name = fm.get("name") or native_name(kind, rel)

    if ide == "cursor" and kind == "rule":
        fm["activation"] = cursor_activation(fm)
    elif ide == "windsurf" and kind == "rule":
        fm["activation"] = fm.get("trigger") or fm.get("activation") or "model_decision"
    elif kind == "rule":
        fm["activation"] = fm.get("activation") or "model_decision"

    if ide == "codex" and kind == "skill" and name.startswith("command-"):
        kind = "command"
        name = name[len("command-"):]
    elif ide == "codex" and kind == "skill" and name.startswith("rule-"):
        kind = "rule"
        name = name[len("rule-"):]
        fm["activation"] = "manual" if parse_bool(fm.get("disable-model-invocation", False)) else "model_decision"
    name = portable_asset_name(name)
    fm["name"] = name
    description = fm.get("description") or first_paragraph(body) or "Imported %s." % kind

    srcdir = os.path.dirname(ap) if kind == "skill" else None
    return base_asset(kind, name, description, body, rel, fm=fm, srcdir=srcdir)


def canonical_rel(asset):
    kind, name = asset["type"], asset["name"]
    if kind == "skill":
        return source_rel("skills", name, "SKILL.md")
    return source_rel("%ss" % kind, "%s.md" % name)


def copy_skill_aux(asset, dest_dir):
    for rel, src in sorted(asset.get("aux", {}).items()):
        dst = os.path.join(dest_dir, rel.replace("/", os.sep))
        if os.path.exists(dst) and read_bytes(dst) != read_bytes(src):
            raise ValueError("canonical aux conflict at %s" % relpath(dst))
        write_bytes(dst, read_bytes(src))


def normalize_body(text):
    lines = []
    for line in strip_marker(text).replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        lines.append(line.rstrip())
    return "\n".join(lines).strip() + "\n"


def normalized_list(value):
    return sorted(value or [])


def aux_hashes(asset):
    hashes = []
    for rel, path in sorted(asset.get("aux", {}).items()):
        hashes.append([rel, hashlib.sha256(read_bytes(path)).hexdigest()])
    return hashes


def fingerprint_payload(asset):
    kind = asset["type"]
    meta = {
        "type": kind,
        "name": asset["name"],
        "description": asset["description"],
        "body": normalize_body(asset["body"]),
        "aux": aux_hashes(asset),
    }
    if kind == "rule":
        meta["activation"] = asset.get("activation") or "model_decision"
        meta["globs"] = normalized_list(asset.get("globs"))
    elif kind == "agent":
        meta["tools"] = normalized_list(asset.get("tools"))
        meta["model"] = asset.get("model") or ""
    elif kind == "command":
        meta["argument-hint"] = asset.get("argument-hint") or ""
        meta["model"] = asset.get("model") or ""
    elif kind == "skill":
        meta["allowed-tools"] = normalized_list(asset.get("allowed-tools"))
    return meta


def asset_fingerprint(asset):
    payload = json.dumps(fingerprint_payload(asset), sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def asset_key(asset):
    return (asset["type"], asset["name"])


def native_record(ide, kind, rel):
    rel = native_display_path(rel)
    if kind == "unsupported-policy":
        return {
            "ide": ide, "kind": kind, "path": rel, "asset": None,
            "fingerprint": None, "error": "Codex execution policy",
            "scope": native_scope(rel),
        }
    asset = native_to_asset(ide, rel, kind)
    return {
        "ide": ide,
        "kind": asset["type"],
        "path": rel,
        "asset": asset,
        "fingerprint": asset_fingerprint(asset),
        "error": None,
        "scope": native_scope(rel),
    }


def canonical_indexes(assets):
    by_key, by_fp, by_name = {}, {}, {}
    for asset in assets:
        by_key[asset_key(asset)] = asset
        by_fp[asset_fingerprint(asset)] = asset
        by_name[asset["name"]] = asset
    return by_key, by_fp, by_name


def cursor_visible_name_from_path(path):
    rel = native_logical_path(path)
    parts = rel.split("/")
    if rel.startswith(".cursor/commands/") and rel.endswith(".md"):
        return os.path.splitext(parts[-1])[0]
    if rel.startswith(".cursor/skills/") and rel.endswith("/SKILL.md"):
        return parts[-2]
    if rel.startswith(".agents/skills/") and rel.endswith("/SKILL.md"):
        return parts[-2]
    return None


def cursor_visibility_key(name):
    name = portable_asset_name(name or "")
    for prefix in ("command-", "rule-", "agent-"):
        if name.startswith(prefix) and len(name) > len(prefix):
            name = name[len(prefix):]
    return slugify(name)


def cursor_visible_generated_records(entries):
    records = []
    for entry in entries:
        if entry.get("mode", "file") != "file":
            continue
        path = entry.get("path")
        name = cursor_visible_name_from_path(path)
        if not name:
            continue
        records.append({
            "path": path,
            "name": name,
            "key": cursor_visibility_key(name),
            "generated": True,
            "kind": entry.get("kind"),
            "target": entry.get("target"),
            "source": entry.get("source"),
        })
    return records


def cursor_visible_native_records(native_records):
    records = []
    for record in native_records:
        asset = record["asset"]
        name = cursor_visible_name_from_path(record["path"])
        if not name:
            continue
        display_name = asset.get("name") or name
        records.append({
            "path": record["path"],
            "name": display_name,
            "key": cursor_visibility_key(display_name),
            "generated": False,
            "kind": asset.get("type"),
            "target": record.get("ide"),
            "source": record["path"],
        })
    return records


def cursor_visible_overlaps(entries, native_records):
    grouped = {}
    for record in (
            cursor_visible_generated_records(entries) +
            cursor_visible_native_records(native_records)):
        if not record["key"]:
            continue
        grouped.setdefault(record["key"], []).append(record)

    overlaps = []
    for key, group in sorted(grouped.items()):
        paths = sorted(set(r["path"] for r in group))
        has_generated = any(r["generated"] for r in group)
        if has_generated and len(paths) > 1:
            overlaps.append({
                "key": key,
                "records": sorted(group, key=lambda r: (not r["generated"], r["path"])),
            })
    return overlaps


def global_priority_key(asset):
    return (asset["type"], cursor_visibility_key(asset["name"]))


def scan_global_native_records():
    records = []
    for ide, kind, rp in scan_native_files(include_global=True, include_repo=False):
        if kind == "unsupported-policy" or has_marker(rp):
            continue
        try:
            records.append(native_record(ide, kind, rp))
        except Exception:
            continue
    return records


def global_priority_blockers_for_asset(asset, global_records=None):
    global_records = global_records if global_records is not None else scan_global_native_records()
    fingerprint = asset_fingerprint(asset)
    key = global_priority_key(asset)
    body = normalize_body(asset["body"]).strip()
    blockers = []
    for record in global_records:
        global_asset = record["asset"]
        reason = None
        if record["fingerprint"] == fingerprint:
            reason = "exact global duplicate"
        elif global_priority_key(global_asset) == key:
            reason = "same %s name" % asset["type"]
        elif (
                global_asset["type"] == asset["type"]
                and len(body) >= 20
                and normalize_body(global_asset["body"]).strip() == body):
            reason = "same normalized body"
        if reason:
            blockers.append({"record": record, "reason": reason})
    return blockers


def global_priority_message(path, blockers):
    first = blockers[0]
    record = first["record"]
    message = (
        "%s matches global asset %s (%s); global assets take priority, "
        "so this repo-native asset will not be promoted into %s/" %
        (path, record["path"], first["reason"], AI_REL))
    if len(blockers) > 1:
        message += " and %d other global match(es)" % (len(blockers) - 1)
    return message


def analyze_native_state(staged_only=False):
    assets = load_assets()
    canonical_by_key, canonical_by_fp, canonical_by_name = canonical_indexes(assets)
    staged = staged_paths() if staged_only else None
    records, unsupported, parse_errors = [], [], []

    for ide, kind, rp in scan_native_files(include_global=not staged_only):
        if staged is not None and rp not in staged:
            continue
        if kind == "unsupported-policy":
            if native_scope(rp) == "repo":
                unsupported.append(
                    "%s: Codex execution policy; keep Codex-only or document separately" % rp)
            continue
        if has_marker(rp):
            continue
        try:
            records.append(native_record(ide, kind, rp))
        except Exception as e:
            parse_errors.append("%s: could not parse native asset (%s)" % (rp, e))

    represented, canonical_conflicts, global_canonical_conflicts = [], [], []
    without_canonical = {}
    global_native_only = []
    global_records = [record for record in records if record["scope"] == "global"]
    global_shadowed = []
    for record in records:
        asset = record["asset"]
        key = asset_key(asset)
        if record["fingerprint"] in canonical_by_fp:
            represented.append(record)
        elif key in canonical_by_key:
            message = (
                "%s: canonical %s asset already exists with different content; resolve manually" %
                (record["path"], AI_REL))
            if record["scope"] == "global":
                global_canonical_conflicts.append(message)
            else:
                canonical_conflicts.append(message)
        elif asset["name"] in canonical_by_name:
            canonical = canonical_by_name[asset["name"]]
            message = (
                "%s: native %s %s overlaps canonical %s %s in %s/; resolve manually" %
                (record["path"], asset["type"], asset["name"],
                 canonical["type"], canonical["name"], AI_REL))
            if record["scope"] == "global":
                global_canonical_conflicts.append(message)
            else:
                canonical_conflicts.append(message)
        else:
            if record["scope"] == "repo":
                blockers = global_priority_blockers_for_asset(asset, global_records)
                if blockers:
                    global_shadowed.append({
                        "record": record,
                        "blockers": blockers,
                    })
                    continue
            without_canonical.setdefault(key, []).append(record)

    exact_groups, native_only, duplicate_conflicts = [], [], []
    for key, group in sorted(without_canonical.items()):
        if all(r["scope"] == "global" for r in group):
            global_native_only.extend(group)
            continue
        by_fp = {}
        for record in group:
            by_fp.setdefault(record["fingerprint"], []).append(record)
        if len(by_fp) > 1:
            paths = ", ".join(r["path"] for r in group)
            duplicate_conflicts.append(
                "%s %s: same name but different native content (%s)" %
                (key[0], key[1], paths))
            continue
        only_group = list(by_fp.values())[0]
        if len(only_group) > 1:
            exact_groups.append(only_group)
        else:
            record = only_group[0]
            if record["scope"] == "global":
                global_native_only.append(record)
            else:
                native_only.append(record)

    possible = []
    by_body = {}
    global_shadowed_paths = set(item["record"]["path"] for item in global_shadowed)
    for record in records:
        if record["path"] in global_shadowed_paths:
            continue
        asset = record["asset"]
        body_key = (asset["type"], normalize_body(asset["body"]))
        by_body.setdefault(body_key, []).append(record)
    for (_kind, _body), group in sorted(by_body.items(), key=lambda item: item[0]):
        if all(r["scope"] == "global" for r in group):
            continue
        names = sorted(set(r["asset"]["name"] for r in group))
        if len(names) > 1:
            possible.append(
                "possible duplicate content with different names: %s" %
                ", ".join(r["path"] for r in group))

    return {
        "assets": assets,
        "canonical_by_key": canonical_by_key,
        "canonical_by_fp": canonical_by_fp,
        "records": records,
        "represented": represented,
        "global_native_only": global_native_only,
        "global_shadowed": global_shadowed,
        "canonical_conflicts": canonical_conflicts,
        "global_canonical_conflicts": global_canonical_conflicts,
        "duplicate_conflicts": duplicate_conflicts,
        "exact_groups": exact_groups,
        "native_only": native_only,
        "possible": possible,
        "unsupported": unsupported,
        "parse_errors": parse_errors,
    }


def write_canonical_asset(asset):
    dest_rel = canonical_rel(asset)
    dest = abspath(dest_rel)
    content = render_canonical(asset)
    if os.path.exists(dest) and read_text(dest) != content:
        raise ValueError("canonical conflict at %s; resolve manually" % dest_rel)
    write_text(dest, content)
    if asset["type"] == "skill":
        copy_skill_aux(asset, os.path.dirname(dest))
    return dest_rel


def adopt_asset(ide, path, global_priority="error"):
    rel = native_display_path(path)
    kind = detect_native(ide, rel)
    if not kind:
        raise ValueError("%s is not a supported %s-native asset" % (rel, ide))
    if native_scope(rel) == "global":
        raise GlobalPriorityError(
            "refusing to promote global asset %s into %s/; "
            "global assets stay user-level and take priority" % (rel, AI_REL))
    if has_marker(rel):
        print("skip %s: already generated from %s/" % (rel, AI_REL))
        return False
    asset = native_to_asset(ide, rel, kind)
    if native_scope(rel) == "repo":
        blockers = global_priority_blockers_for_asset(asset)
        if blockers:
            message = global_priority_message(rel, blockers)
            if global_priority == "skip":
                print("skip %s: %s" % (rel, message))
                return False
            raise GlobalPriorityError(message)
    _by_key, by_fp, _by_name = canonical_indexes(load_assets())
    if asset_fingerprint(asset) in by_fp:
        print("skip %s: already represented in %s/" % (rel, AI_REL))
        return False
    dest_rel = write_canonical_asset(asset)
    print("adopted %s -> %s" % (rel, dest_rel))
    return True


def scan_native_files(include_global=True, include_repo=True):
    found = []
    if include_repo:
        for root in REPO_NATIVE_ROOTS:
            base = abspath(root)
            if not os.path.isdir(base):
                continue
            for dirpath, _dirs, files in os.walk(base):
                for f in files:
                    rp = relpath(os.path.join(dirpath, f))
                    ide = ide_from_path(rp)
                    kind = detect_native(ide, rp) if ide else None
                    if kind:
                        found.append((ide, kind, rp))
    if include_global:
        home = os.path.abspath(os.path.expanduser("~"))
        for ide, root in GLOBAL_NATIVE_ROOTS:
            base = os.path.join(home, root.replace("/", os.sep))
            if not os.path.isdir(base):
                continue
            for dirpath, _dirs, files in os.walk(base):
                for f in files:
                    rp = display_path_for_abs(os.path.join(dirpath, f))
                    kind = detect_native(ide, rp)
                    if kind:
                        found.append((ide, kind, rp))
    return sorted(found, key=lambda x: x[2])


def represented_native_paths(assets):
    """Repo-native markerless files whose content is already captured verbatim
    in canonical `.ai/` (exact fingerprint match).

    These are the surfaces an earlier `adopt`/`reconcile` promoted; sync may
    refresh them in place because the same asset already lives in `.ai/`.
    Divergent or unrelated markerless files never match, so they remain
    protected by the markerless-overwrite guard.
    """
    _by_key, by_fp, _by_name = canonical_indexes(assets)
    paths = set()
    for ide, kind, rp in scan_native_files(include_global=False):
        if kind == "unsupported-policy" or has_marker(rp):
            continue
        try:
            record = native_record(ide, kind, rp)
        except Exception:
            continue
        if record["fingerprint"] in by_fp:
            paths.add(record["path"])
    return paths


def command_adopt(args):
    try:
        if args.global_scope:
            raise GlobalPriorityError(
                "refusing to promote global assets into %s/; "
                "global assets stay user-level and take priority" % AI_REL)
        if args.all:
            adopted = 0
            unresolved = []
            for ide, kind, rp in scan_native_files(include_global=False):
                if kind == "unsupported-policy" or has_marker(rp):
                    continue
                try:
                    if adopt_asset(ide, rp, global_priority="skip"):
                        adopted += 1
                except ValueError as e:
                    # One asset that conflicts with existing `.ai/` content (or
                    # fails to parse) must not abort adoption of everything else.
                    unresolved.append(rp)
                    print("skip %s: %s" % (rp, e))
            print("adopted %d native assets" % adopted)
            if unresolved:
                print(
                    "%d native asset(s) still need manual resolution; "
                    "review Blocking items before syncing with: %s" %
                    (len(unresolved), shell_command([COMMAND_NAME, "status"])))
            return 0
        if not args.ide or not args.path:
            raise ValueError("usage: adopt <ide> <path> or adopt --all")
        adopt_asset(args.ide, args.path)
        return 0
    except ValueError as e:
        print("ERROR: %s" % e)
        return 1


def staged_paths():
    try:
        out = subprocess.check_output(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACMR"],
            cwd=REPO, universal_newlines=True)
    except Exception:
        return None
    return set(x.strip() for x in out.splitlines() if x.strip())


def find_doctor_issues(staged_only=False):
    assets = load_assets()
    texts, copies, managed, entries, degradations = build(assets)
    drift = compare_outputs(texts, copies, managed, entries)
    state = analyze_native_state(staged_only=staged_only)
    state["drift"] = drift
    state["degradations"] = degradations
    state["canonical_ide_prefixes"] = canonical_ide_prefix_issues(assets)
    state["cursor_visible_overlaps"] = cursor_visible_overlaps(entries, state["records"])
    return state


def command_doctor(args):
    state = find_doctor_issues(args.staged)
    conflicts = state["canonical_conflicts"] + state["duplicate_conflicts"] + state["parse_errors"]
    global_conflicts = state["global_canonical_conflicts"]
    has_blocking = any([
        state["drift"], state["native_only"], state["exact_groups"],
        conflicts, state["unsupported"], state["canonical_ide_prefixes"],
    ])
    if not any([
            has_blocking, global_conflicts, state["represented"],
            state["possible"], state["cursor_visible_overlaps"],
            state["global_shadowed"], state["degradations"]]):
        print("Doctor found no agentic config issues.")
        return 0

    if state["exact_groups"]:
        print("Exact duplicate native groups:")
        for group in state["exact_groups"]:
            asset = group[0]["asset"]
            print("  %s %s:" % (asset["type"], asset["name"]))
            for record in group:
                print("    %s" % record["path"])
            print("    suggested: %s" % shell_command([
                COMMAND_NAME, "reconcile", asset["type"], asset["name"]]))
        print("  all exact groups: %s" %
              shell_command([COMMAND_NAME, "reconcile", "--all-exact"]))
    repo_represented = [r for r in state["represented"] if r["scope"] == "repo"]
    global_represented = [r for r in state["represented"] if r["scope"] == "global"]
    if repo_represented:
        print("Native duplicates already represented in %s/:" % AI_REL)
        for record in repo_represented:
            asset = record["asset"]
            print("  %s -> %s %s %s" %
                  (record["path"], AI_REL, asset["type"], asset["name"]))
        print("  optional cleanup: %s" %
              shell_command([COMMAND_NAME, "clean", "--native-duplicates"]))
    if global_represented:
        print("Global native duplicates already represented in %s/:" % AI_REL)
        for record in global_represented:
            asset = record["asset"]
            print("  %s -> %s %s %s" %
                  (record["path"], AI_REL, asset["type"], asset["name"]))
        print("  global assets are read-only and take priority; leave them in place.")
    if state["native_only"]:
        print("Native-only assets:")
        for record in state["native_only"]:
            print("  %s: native-only" % record["path"])
            print("    suggested: %s" % shell_command([
                COMMAND_NAME, "adopt", record["ide"], record["path"]]))
    if state["drift"]:
        print("Generated but stale:")
        for item in state["drift"]:
            print("  %s" % item)
        print("  run %s" % shell_command([COMMAND_NAME]))
    if conflicts:
        print("Canonical conflicts:")
        for item in conflicts:
            print("  %s" % item)
    if global_conflicts:
        print("Global native overlaps:")
        for item in global_conflicts:
            print("  %s" % item)
    if state["global_shadowed"]:
        print("Repo-native assets shadowed by global assets:")
        for item in state["global_shadowed"]:
            record = item["record"]
            print("  %s: %s" %
                  (record["path"], global_priority_message(record["path"], item["blockers"])))
    if state["cursor_visible_overlaps"]:
        print("Cursor-visible overlaps:")
        for overlap in state["cursor_visible_overlaps"]:
            print("  %s:" % overlap["key"])
            for record in overlap["records"]:
                origin = "generated %s %s" % (record["target"], record["kind"])
                if not record["generated"]:
                    origin = "native %s %s" % (record["target"], record["kind"])
                print("    %s (%s)" % (record["path"], origin))
                if record["generated"]:
                    print("      suggested: %s" % shell_command([
                        COMMAND_NAME, "demote", "cursor", record["path"]]))
                    if record["target"] != "cursor":
                        print(
                            "      warning: suppresses a %s-target projection visible to Cursor" %
                            record["target"])
    if state["canonical_ide_prefixes"]:
        print("IDE-specific canonical names:")
        for item in state["canonical_ide_prefixes"]:
            print("  %s" % item)
    if state["possible"]:
        print("Possible duplicates:")
        for item in state["possible"]:
            print("  %s" % item)
    if state["unsupported"]:
        print("Unsupported or Codex-only assets:")
        for item in state["unsupported"]:
            print("  %s" % item)
    if state["degradations"] and not args.staged:
        print("Degraded mappings:")
        for item in state["degradations"]:
            print("  %s" % item)
    print_stealth_skips()
    return 1 if any([
        state["drift"], state["native_only"], state["exact_groups"],
        conflicts, state["unsupported"], state["canonical_ide_prefixes"],
    ]) else 0


STATUS_DETAIL_LIMIT = 8


def print_limited(items, limit=STATUS_DETAIL_LIMIT, verbose=False):
    effective_limit = len(items) if verbose else limit
    shown = list(items[:effective_limit])
    for item in shown:
        print("  %s" % item)
    remaining = len(items) - len(shown)
    if remaining > 0:
        print("  ... and %d more" % remaining)
    return remaining > 0


def status_conflicts(state):
    return state["canonical_conflicts"] + state["duplicate_conflicts"] + state["parse_errors"]


def command_status(args):
    if args.check:
        return command_sync(check=True)

    state = find_doctor_issues(False)
    conflicts = status_conflicts(state)
    canonical_blockers = state["canonical_conflicts"] + state["parse_errors"]
    duplicate_blockers = state["duplicate_conflicts"]
    repo_represented = [r for r in state["represented"] if r["scope"] == "repo"]
    global_represented = [r for r in state["represented"] if r["scope"] == "global"]
    verbose = args.verbose
    truncated_details = False

    blocking = []
    if conflicts:
        blocking.append("%d conflict(s) need a human decision." % len(conflicts))
    if state["native_only"]:
        blocking.append("%d native-only asset(s) can be imported." % len(state["native_only"]))
    if state["exact_groups"]:
        blocking.append("%d exact duplicate group(s) can be reconciled." % len(state["exact_groups"]))
    if state["canonical_ide_prefixes"]:
        blocking.append("%d canonical asset(s) use IDE-specific names." %
                        len(state["canonical_ide_prefixes"]))

    optional_count = (
        len(state["unsupported"]) + len(state["cursor_visible_overlaps"]) +
        len(state["degradations"]) + len(state["possible"]) +
        len(state["global_shadowed"]) + len(state["global_canonical_conflicts"]) +
        len(global_represented)
    )

    print("Agentic Config Status")
    print("")
    if blocking:
        print("Blocking:")
        for item in blocking:
            print("  %s" % item)
        if conflicts:
            print("  Conflicts:")
            truncated_details = print_limited(
                conflicts, verbose=verbose) or truncated_details
        if state["native_only"]:
            print("  Native-only assets:")
            truncated_details = print_limited(
                ["%s" % r["path"] for r in state["native_only"]],
                verbose=verbose) or truncated_details
        if state["exact_groups"]:
            print("  Exact duplicate groups:")
            truncated_details = print_limited([
                "%s %s" % (group[0]["asset"]["type"], group[0]["asset"]["name"])
                for group in state["exact_groups"]
            ], verbose=verbose) or truncated_details
        print("")
    else:
        print("Blocking:")
        print("  None")
        print("")

    if state["drift"]:
        print("Needs update:")
        print("  %d generated output(s) are stale." % len(state["drift"]))
        truncated_details = print_limited(
            state["drift"], verbose=verbose) or truncated_details
        print("")
    else:
        print("Needs update:")
        print("  None")
        print("")

    if repo_represented:
        print("Recommended cleanup:")
        print("  %d native duplicate(s) are already represented in %s/." %
              (len(repo_represented), AI_REL))
        print("  Run: %s clean --native-duplicates" % COMMAND_NAME)
        print("")
    else:
        print("Recommended cleanup:")
        print("  None")
        print("")

    if optional_count:
        print("Optional / informational:")
        if state["unsupported"]:
            print("  %d unsupported or Codex-only asset(s)." % len(state["unsupported"]))
        if state["cursor_visible_overlaps"]:
            print("  %d Cursor-visible overlap group(s)." %
                  len(state["cursor_visible_overlaps"]))
        if state["degradations"]:
            print("  %d degraded mapping note(s)." % len(state["degradations"]))
        if state["possible"]:
            print("  %d possible duplicate content note(s)." % len(state["possible"]))
        if state["global_shadowed"]:
            print("  %d repo-native asset(s) are shadowed by global assets." %
                  len(state["global_shadowed"]))
        if state["global_canonical_conflicts"]:
            print("  %d global native overlap(s)." %
                  len(state["global_canonical_conflicts"]))
        if global_represented:
            print("  %d global native duplicate(s) are represented in %s/." %
                  (len(global_represented), AI_REL))
        print("  Run %s doctor for full diagnostics." % COMMAND_NAME)
        print("")
    else:
        print("Optional / informational:")
        print("  None")
        print("")

    if truncated_details:
        print("More detail:")
        print("  Run %s status --verbose for full lists." % COMMAND_NAME)
        print("")

    print("Next step:")
    if canonical_blockers:
        print("  Resolve the conflicts above, then run %s sync." % COMMAND_NAME)
    elif duplicate_blockers:
        print("  Run %s import --all to import unambiguous assets." % COMMAND_NAME)
        print("  Resolve any conflicts that remain, then run %s sync." % COMMAND_NAME)
    elif state["exact_groups"]:
        print("  Run %s import --exact-duplicates." % COMMAND_NAME)
    elif state["native_only"]:
        print("  Run %s import --all." % COMMAND_NAME)
    elif state["canonical_ide_prefixes"]:
        print("  Rename the IDE-specific canonical assets, then run %s sync." % COMMAND_NAME)
    elif state["drift"]:
        print("  Run %s sync." % COMMAND_NAME)
    elif repo_represented:
        print("  Optional: run %s clean --native-duplicates." % COMMAND_NAME)
    elif optional_count:
        print("  No blocking action. Review optional items only if they matter to your workflow.")
    else:
        print("  No action needed.")
    print_stealth_skips()

    if args.verbose:
        print("")
        print("Verbose doctor report:")
        class DoctorArgs(object):
            staged = False
        command_doctor(DoctorArgs())
        return 1 if blocking or state["drift"] else 0

    return 1 if blocking or state["drift"] else 0


def reconcile_group(group):
    asset = group[0]["asset"]
    dest_rel = write_canonical_asset(asset)
    print("reconciled %s %s -> %s" %
          (asset["type"], asset["name"], dest_rel))
    for record in group:
        print("  source: %s" % record["path"])
    return dest_rel


def command_reconcile(args):
    try:
        state = analyze_native_state(staged_only=False)
        groups = state["exact_groups"]
        if args.all_exact:
            if not groups:
                print("No exact duplicate native groups to reconcile.")
                return 0
            for group in groups:
                reconcile_group(group)
            print("Reconciled %d exact duplicate groups." % len(groups))
            return 0

        if not args.kind or not args.name:
            print("ERROR: usage: reconcile <kind> <name> or reconcile --all-exact")
            return 1
        for group in groups:
            asset = group[0]["asset"]
            if asset["type"] == args.kind and asset["name"] == args.name:
                reconcile_group(group)
                return 0
        print("ERROR: no exact duplicate native group found for %s %s" %
              (args.kind, args.name))
        return 1
    except ValueError as e:
        print("ERROR: %s" % e)
        return 1


def entry_for_path(entries, path):
    for entry in entries:
        if entry.get("mode", "file") == "file" and entry.get("path") == path:
            return entry
    return None


def demotion_record(consumer, path, group, assets):
    primary = entry_for_path(group, path) or group[0]
    assets_by_source = dict((asset["srcrel"], asset) for asset in assets)
    asset = assets_by_source.get(primary.get("source"))
    name = asset["name"] if asset else cursor_visible_name_from_path(path)
    return {
        "consumer": consumer,
        "path": path,
        "source": primary.get("source"),
        "target": primary.get("target"),
        "kind": primary.get("kind"),
        "name": name,
        "group": [entry["path"] for entry in group],
    }


def validate_demote_args(consumer, path):
    if consumer not in TARGETS:
        raise ValueError("unknown consumer IDE %s (expected one of %s)" %
                         (consumer, ", ".join(TARGETS)))
    return normalize_repo_rel_path(path)


def explain_missing_demotable_path(path):
    if os.path.exists(abspath(path)) and not has_marker(path):
        raise ValueError(
            "refusing to demote markerless native file at %s; "
            "demote a generated competing path instead" % path)
    raise ValueError("%s is not a current generated projection from %s/" %
                     (path, AI_REL))


def upsert_demotion(record):
    records = read_demotions()
    key = (record["consumer"], record["path"])
    updated = []
    replaced = False
    for existing in records:
        if (existing.get("consumer"), existing.get("path")) == key:
            updated.append(record)
            replaced = True
        else:
            updated.append(existing)
    if not replaced:
        updated.append(record)
    write_demotions(updated)
    return replaced


def command_demote(args):
    try:
        path = validate_demote_args(args.consumer, args.path)
        assets = load_assets()
        _texts, _copies, _managed, entries, _degradations = build(
            assets, apply_saved_demotions=False)
        group = generated_output_group(path, entries)
        if not group:
            explain_missing_demotable_path(path)
        old_files = manifest_files_by_path(read_manifest_entries())
        for entry in group:
            if os.path.exists(abspath(entry["path"])):
                assert_safe_file_mutation(
                    entry["path"], old_files.get(entry["path"]), "demote")
        record = demotion_record(args.consumer, path, group, assets)
        replaced = upsert_demotion(record)
        action = "Updated demotion" if replaced else "Demoted"
        print("%s for %s: %s" % (action, args.consumer, path))
        for entry in group:
            print("  suppresses %s" % entry["path"])
        if record["target"] != args.consumer:
            print(
                "  warning: suppresses a %s-target projection visible to %s" %
                (record["target"], args.consumer))
        return command_sync(check=False)
    except (SafetyError, ValueError) as e:
        print("ERROR: %s" % e)
        return 1


def command_promote(args):
    try:
        path = validate_demote_args(args.consumer, args.path)
        records = read_demotions()
        kept = [
            record for record in records
            if not (record.get("consumer") == args.consumer and record.get("path") == path)
        ]
        if len(kept) == len(records):
            print("No demotion found for %s: %s" % (args.consumer, path))
            return 0
        write_demotions(kept)
        print("Promoted for %s: %s" % (args.consumer, path))
        return command_sync(check=False)
    except (SafetyError, ValueError) as e:
        print("ERROR: %s" % e)
        return 1


def remove_file_if_exists(path):
    if os.path.isfile(path):
        os.remove(path)
        return True
    return False


def remove_native_record(record):
    asset = record["asset"]
    removed = []
    if asset["type"] == "skill":
        root = os.path.dirname(native_abspath(record["path"]))
        skill_md = os.path.join(root, "SKILL.md")
        if remove_file_if_exists(skill_md):
            removed.append(display_path_for_abs(skill_md))
        for rel in sorted(asset.get("aux", {})):
            aux_path = os.path.join(root, rel.replace("/", os.sep))
            if remove_file_if_exists(aux_path):
                removed.append(display_path_for_abs(aux_path))
        boundary = os.path.dirname(root) if record["scope"] == "global" else REPO
        prune_empty_dirs(removed, boundary=boundary)
    else:
        path = native_abspath(record["path"])
        if remove_file_if_exists(path):
            removed.append(record["path"])
            boundary = os.path.dirname(os.path.dirname(path)) if record["scope"] == "global" else REPO
            prune_empty_dirs([record["path"]], boundary=boundary)
    return removed


def command_clean(args):
    if args.global_scope:
        print(
            "ERROR: refusing to clean global native assets; "
            "global assets stay user-level and take priority")
        return 1
    removed = []
    try:
        for entry in read_manifest_entries():
            if entry.get("mode", "file") != "file":
                continue
            p = entry.get("path")
            if not p or not p.startswith(GENERATED_PREFIXES):
                continue
            if os.path.exists(abspath(p)):
                assert_safe_file_mutation(p, entry, "clean")
            if remove_file_if_exists(abspath(p)):
                removed.append(p)
    except SafetyError as e:
        print("ERROR: %s" % e)
        return 1
    prune_empty_dirs(removed)

    native_removed = []
    if args.native_duplicates:
        state = analyze_native_state(staged_only=False)
        for record in state["represented"]:
            if record["scope"] == "global":
                continue
            else:
                native_removed.extend(remove_native_record(record))

    print("Cleaned %d generated projection files." % len(removed))
    for p in removed:
        print("  removed %s" % p)
    if args.native_duplicates:
        print("Cleaned %d exact native duplicate files." % len(native_removed))
        for p in native_removed:
            print("  removed %s" % p)
    return 0


def command_bootstrap(_args):
    rc = command_sync(check=False)
    if rc:
        return rc
    print("")
    print("Bootstrap doctor report:")
    class DoctorArgs(object):
        staged = False
    doctor_rc = command_doctor(DoctorArgs())
    print("")
    if doctor_rc:
        print("Bootstrap generated local IDE projections, but doctor found follow-up work above.")
        print("Resolve the reported items, then rerun %s bootstrap." % COMMAND_NAME)
    else:
        print("Bootstrap complete. Your local IDE projections have been generated.")
        print("Generated IDE folders may be gitignored; edit %s/ or use adopt/reconcile." % AI_REL)
    return doctor_rc


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv == ["--check"]:
        return command_sync(check=True)
    if not argv:
        return command_sync(check=False)

    cmd = argv[0]
    if cmd == "sync":
        return command_sync(check=False)
    if cmd == "check":
        return command_sync(check=True)
    if cmd == "doctor":
        ap = argparse.ArgumentParser(prog="sync.py doctor")
        ap.add_argument("--staged", action="store_true")
        return command_doctor(ap.parse_args(argv[1:]))
    if cmd == "status":
        ap = argparse.ArgumentParser(prog="sync.py status")
        ap.add_argument("--verbose", action="store_true")
        ap.add_argument("--check", action="store_true")
        return command_status(ap.parse_args(argv[1:]))
    if cmd == "adopt":
        ap = argparse.ArgumentParser(prog="sync.py adopt")
        ap.add_argument("ide", nargs="?")
        ap.add_argument("path", nargs="?")
        ap.add_argument("--all", action="store_true")
        ap.add_argument("--global", dest="global_scope", action="store_true")
        args = ap.parse_args(argv[1:])
        if args.ide == "--all":
            args.all = True
            args.ide = None
        return command_adopt(args)
    if cmd == "reconcile":
        ap = argparse.ArgumentParser(prog="sync.py reconcile")
        ap.add_argument("kind", nargs="?")
        ap.add_argument("name", nargs="?")
        ap.add_argument("--all-exact", action="store_true")
        return command_reconcile(ap.parse_args(argv[1:]))
    if cmd == "demote":
        ap = argparse.ArgumentParser(prog="sync.py demote")
        ap.add_argument("consumer")
        ap.add_argument("path")
        return command_demote(ap.parse_args(argv[1:]))
    if cmd == "promote":
        ap = argparse.ArgumentParser(prog="sync.py promote")
        ap.add_argument("consumer")
        ap.add_argument("path")
        return command_promote(ap.parse_args(argv[1:]))
    if cmd == "clean":
        ap = argparse.ArgumentParser(prog="sync.py clean")
        ap.add_argument("--native-duplicates", action="store_true")
        ap.add_argument("--global", dest="global_scope", action="store_true")
        return command_clean(ap.parse_args(argv[1:]))
    if cmd == "bootstrap":
        ap = argparse.ArgumentParser(prog="sync.py bootstrap")
        return command_bootstrap(ap.parse_args(argv[1:]))

    print("ERROR: unknown command %s" % cmd)
    return 2


if __name__ == "__main__":
    sys.exit(main())
